### ISSUE TITLE
Strategy for attaching first layer

### ISSUE THREAD

**Issue by kefir-** [slic3r/Slic3r#1181]
I often experience that the very beginning of a print doesn't attach very well, and leaves a lump or strip dangling on my print. This can often be worked around by printing a skirt, but if there is a lump/strip it can get in the way and cause problems further down the road, so it would be good to avoid if possible.

I'm curious whether it'd be possible to get better initial anchoring on the first layer if the nozzle started closer to the bed, perhaps even at Z=0, and lifted up while extruding plastic, perhaps over a short distance, ie. 0-2 mm. After that, we should hopefully have anchored the first line quite well, and can continue as normal.

**Comment by lordofhyphens** [comment]
A brim would also give you more extrusion amount for priming purposes, but has other side effects.
Could you see if #3349 helps at all with this problem?

**Comment by lordofhyphens** [comment]
@kefir- are you still seeing this problem with 1.3.0?

**Comment by kefir-** [comment]
Not an issue I'm bother with any more, we can close this.
