### ISSUE TITLE
Dialogue corruption on save print settings

### ISSUE THREAD

**Issue by darrenfreeman** [slic3r/Slic3r#2255]
Slic3r 1.2.0 experimental

I hit save under "Print Settings", and instantly all the numerical input boxes get populated with three copies of the text that was in them.

**Comment by lordofhyphens** [comment]
I haven't seen this in 1.2.9 or 1.3.0, so pretty sure it was fixed :)

**Comment by darrenfreeman** [comment]
I see it 100% of the time on 1.2.9 stable.

**Comment by darrenfreeman** [comment]
It's an epic pain in the backside, so please reopen. It renders the UI nearly unusable until you figure out how to work around it.

**Comment by lordofhyphens** [comment]
What OS? I can't reproduce this on 1.2.9 for Windows and I have never seen it on Linux. 
You are probably going to have to give exact reproduction steps (with screenshots).

**Comment by darrenfreeman** [comment]
OS: 64-bit openSUSE, has done this on a few versions. I'm currently using Tumbleweed for the latest of everything.

Steps to reproduce:
1. Run the application.
2. Go to print settings -> Speed
3. Hit save.

The text boxes are now corrupted as in the attached image.

![slic3r](https://cloud.githubusercontent.com/assets/4440028/16737865/9ff73a78-47d6-11e6-8370-7f5966eaec25.png)

The correct behaviour can be restored by mouse left clicking in any text box, then in a different text box. This triggers an update and then the correct values are displayed.

**Comment by lordofhyphens** [comment]
Are you using the prebuilt package for Linux from slic3r.org, compiled from the tags or your distro's packages?

**Comment by lordofhyphens** [comment]
Strongly suspect this is related to OpenSUSE's library setup, as the package from slic3r.org for 1.2.9 does not show this behavior with the provided reproduction step on Debian Jessie.

**Comment by Barethan** [comment]
Issue is non-existent on Debian Jessie with slic3r 1.2.9.  wxWidgets is version 3.0.2.

**Comment by ctag** [comment]
I'm also unable to recreate the text artifacts on Archlinux with the [slic3r-bin AUR package](https://aur.archlinux.org/packages/slic3r-bin/).

**Comment by ctag** [comment]
I installed OpenSUSE Tumbleweed x64 on a virtualbox vm, built Slic3r, and couldn't replicate the issue. 

I'm confident the artifacts on your screen are caused by some sort of conflict that the package maintainer can resolve. There currently are [zero bug reports](https://bugzilla.opensuse.org/buglist.cgi?quicksearch=slic3r&list_id=4413533) on the OpenSUSE bugs site about Slic3r, so you'd likely have to submit this to see it fixed. 

That, or build from source. I was able to build Slic3r from the [OpenSUSE 13.2 instructions](https://github.com/alexrj/Slic3r/wiki/Running-Slic3r-from-git-on-GNU-Linux), with a few changes:
- Install boost-devel, freeglut, cpanm
- Install perl-Parse-PMFile by breaking the package dependency (option 2)
- cpanm install OpenGL as administrator with the $DISPLAY variable properly set (it wasn't for me)

**Comment by lordofhyphens** [comment]
@darrenfreeman if you still have the problem when building from source, then the problem is likely something with your system libs, which is not something we can fix here.

**Comment by darrenfreeman** [comment]
Wow, a lot of activity and questions while I was asleep :) Okay, in order..

I am using the prebuilt package from slic3r.org, http://dl.slic3r.org/linux/slic3r-linux-x86_64-1-2-9-stable.tar.gz

rpm -qa | grep wx
libwx_gtk2u_gizmos-2_8-0-stl-2.8.12-27.12.x86_64
libwx_baseu_xml-2_8-0-stl-2.8.12-27.12.x86_64
libwx_gtk2u_adv-2_8-0-stl-2.8.12-27.12.x86_64
libwx_gtk2u_adv-2_8-0-compat-lib-stl-2.8.12-27.12.x86_64
plplot-wxwidgets-5.11.1-5.2.x86_64
libwx_gtk2u_qa-2_8-0-stl-2.8.12-27.12.x86_64
libwx_baseu-suse1-3.0.2-4.2.x86_64
python-wxWidgets-2.8.12.1-12.5.x86_64
python-wxWidgets-lang-2.8.12.1-12.5.x86_64
libwx_gtk2u_html-2_8-0-stl-2.8.12-27.12.x86_64
libwx_baseu-2_8-0-compat-lib-stl-2.8.12-27.12.x86_64
libwx_gtk2u_core-2_8-0-compat-lib-stl-2.8.12-27.12.x86_64
libwx_gtk2u_xrc-2_8-0-stl-2.8.12-27.12.x86_64
libwx_gtk2u_media-2_8-0-stl-2.8.12-27.12.x86_64
libwx_gtk2u_richtext-2_8-0-stl-2.8.12-27.12.x86_64
libwx_gtk2u_aui-2_8-0-stl-2.8.12-27.12.x86_64
libwx_gtk2u_core-2_8-0-stl-2.8.12-27.12.x86_64
libwx_gtk2u_stc-2_8-0-stl-2.8.12-27.12.x86_64
libwx_baseu_net-2_8-0-stl-2.8.12-27.12.x86_64
libwx_gtk2u_gl-2_8-0-stl-2.8.12-27.12.x86_64
libwx_baseu-2_8-0-stl-2.8.12-27.12.x86_64
wxcam-1.1-4.98.x86_64
wxWidgets-lang-2.8.12-27.12.noarch
libwx_gtk2u_core-suse1-3.0.2-4.2.x86_64
wxWidgets-compat-lib-config-2.8.12-27.12.x86_64

Please note that there are multiple openSUSE packages for wx, depending on compile-time options. If you're not sure about the naming convention, please look it up. It could be the culprit.

"I installed OpenSUSE Tumbleweed x64 on a virtualbox vm, built Slic3r, and couldn't replicate the issue."

Yes, but did you try the prebuilt package from slic3r.org? I've seen this on different installs of openSUSE, on different machines. And I reported the issue for an earlier version of slic3r, so it's been present across a number of library versions.

"There currently are zero bug reports on the OpenSUSE bugs site about Slic3r, so you'd likely have to submit this to see it fixed."

I don't think this proves anything. I never would have considered reporting this to openSUSE. It's a package I got from slic3r.org, not from them.

I will have a go at building from source, but not today.

Please, don't close the bug report just because you can't replicate it (yet). You're basically saying that I'm making it up, the bug doesn't exist. Yet I've sent you a screen-shot. It shouldn't matter if it only occurs rarely, the fact is it's been happening for me for 22 months, across multiple OS versions and on multiple PCs, and this is the first that we've tried to diagnose it.

**Comment by lordofhyphens** [comment]
It's only been occurring on one *distro*, and I have been unable to reproduce it with another distro (or another OS), it hasn't been reported on OSX. 

That it apparently works when built from source means that it's interacting weirdly with your system libraries.

**Comment by darrenfreeman** [comment]
Well, then let me know of some things that I can try.

**Comment by lordofhyphens** [comment]
Build from source or use a package from your distro.

**Comment by lordofhyphens** [comment]
@darrenfreeman you can use the AppImage now from dl.slic3r.org/dev/linux or 1.3.0 https://github.com/slic3r/Slic3r/releases/tag/1.3.0
