### ISSUE TITLE
Support 3MF specification

### ISSUE THREAD

**Issue by harriv** [slic3r/Slic3r#2811]
It's a brand new specification: http://3mf.io/what-is-3mf/3mf-specification/

**Comment by alexrj** [comment]
Yeah, saw that. But I couldn't find any example file. The specs are not that clear, despite the presence of the XSD. Can you find an example file?

**Comment by harriv** [comment]
I'll look. It may take some time before there's clear examples around..

**Comment by harriv** [comment]
Windows 3D Printing SDK should has have sample files: https://msdn.microsoft.com/en-us/windows/hardware/bg183398.aspx

Unfortunately it only install on Windows 8+, which I don't have.

**Comment by drayde** [comment]
Still need an example 3mf file? Email me at mail-at-andreaskahler.com

**Comment by lonelymyp** [comment]
sample mug:
3mf: https://drive.google.com/file/d/0B2sGop41unyOamt0aWJZMEVyMUU/view?usp=sharing
stl: https://drive.google.com/file/d/0B2sGop41unyOQ0c4aHFseER4QUU/view?usp=sharing
![cam00034](https://cloud.githubusercontent.com/assets/2085051/7787133/e5ec259e-0203-11e5-9eb4-5bb97292f00e.jpg)

**Comment by rogersachan** [comment]
@alexrj The whole thing is now open source https://github.com/3MFConsortium and is supported by Cuda.

**Comment by rogersachan** [comment]
Their documentation is noticeably better now, and is implemented and a list of implementations are here: http://3mf.io/adoption/ .

**Comment by lordofhyphens** [comment]
Yeah, I have been keeping an eye on lib3mf, just haven't had the time to
dive in and implement a link to our internal formats.

**Comment by rogersachan** [comment]
Is this issue resolved as of #4046 ?

**Comment by lordofhyphens** [comment]
Yes, it should be.
