### ISSUE TITLE
allow changing filament settings at n layer height (M600)

### ISSUE THREAD

**Issue by robse-git** [slic3r/Slic3r#3135]
Hi,

since Marlin supports M600 filament-change command, it would be handy to be able to change the filaments settings (temperature / diameter / multiplier) at a specific layer height.

M600 gcode support from the slic3r GUI would be nice too

Thank you

**Comment by lordofhyphens** [comment]
This can be handled with a post-processing script, or just editing the
gcode for a single object. For multiple objects or vase mode things get a
little harder.

**Comment by robseee** [comment]
how can you change the multiplier with a post-processing script ?

**Comment by lordofhyphens** [comment]
Make use of m221, which changes the flow extrusion rate.

**Comment by lordofhyphens** [comment]
There might also be something you could do with the modifier meshes.

**Comment by lordofhyphens** [comment]
Actually, the other semitrivial way you can make this work is to tell slic3r you have multiple extruders and change the toolchange gcode to insert M600. Do a find/replace in the gcode to remove the toolchange command itself (basically everything but T0).

**Comment by lordofhyphens** [comment]
Okay, with #3590 and toolchange gcode, tell Slic3r you have 2 extruders, define a modifier mesh to cover the area you want to change to, and put M600 in the toolchange gcode. 

Should work.
