### ISSUE TITLE
Strange infill artifact when slicing STL

### ISSUE THREAD

**Issue by kelchm** [slic3r/Slic3r#3312]
### Version

1.2.9
### Operating system type + version

OS X 10.11.4
### Behavior

I'm noticing a strange artifact when slicing this STL.

![screen shot 2016-04-22 at 11 11 02 pm](https://cloud.githubusercontent.com/assets/172301/14758976/df695b2c-08df-11e6-9cff-db21d2e9f510.png)
![screen shot 2016-04-22 at 11 11 17 pm](https://cloud.githubusercontent.com/assets/172301/14758977/df697b5c-08df-11e6-85c7-029e8e46f747.png)
#### STL/Config (.ZIP) where problem occurs

[T-RexSkull_Skull.stl.zip](https://github.com/alexrj/Slic3r/files/232780/T-RexSkull_Skull.stl.zip)
[Slic3r_config_bundle.ini.zip](https://github.com/alexrj/Slic3r/files/232781/Slic3r_config_bundle.ini.zip)

**Comment by Mikk36** [comment]
Issue not present with latest git version.
