### ISSUE TITLE
Just an idea - automatic generation of "mouse ear" brim

### ISSUE THREAD

**Issue by DjDemonD** [slic3r/Slic3r#3700]
_Is this a new feature request?_Y

I know many people printing ABS onto certain surfaces struggle with bed adhesion and using a brim is not always sufficient. Some advocate, and I use this a lot, using circular pads at the extremities of an object to improve adhesion "mouse ears" and these work extremely well. I've attached an image, one part in ABS with a 5mm brim with warp that has detached from the bed, and the same part with "ears" which has not.

Would it be possible to generate this type of support automatically? This would improve ABS (and other materials) adhesion and save users a fair bit of time adding these features, part by part in CAD? I suspect with them a brim is unnecessary and they may even be a more efficient use of filament, certainly easier to trim away afterwards.
![20170208_203717](https://cloud.githubusercontent.com/assets/17222445/22756302/8c406022-ee3e-11e6-9ec2-c5f58c110716.jpg)
![20170208_203944](https://cloud.githubusercontent.com/assets/17222445/22756374/d43f0716-ee3e-11e6-9504-99c48e25a211.jpg)

**Comment by konvoj** [comment]
I vote for this feature as well. ABS is nasty around the corners and standard brim generated by Slic3r is not enough for some prints.

**Comment by alexrj** [comment]
#1316

**Comment by lordofhyphens** [comment]
Did some initial investigation, I think collecting the convex points in the bottom islands would give you the correct origin points; center circles there and subtract the object (similar to how brims appear to be done).

**Comment by lordofhyphens** [comment]
Fixed via #4691
