### ISSUE TITLE
Length and Extra length on restart override in filament settings

### ISSUE THREAD

**Issue by poikilos** [slic3r/Slic3r#4215]
### Version
1.3.0-dev (git ~Nov 29 2017) 
commit unknown since Antergos cleared my pamac-build-tmp

### Operating system type + version
Antergos (~Nov 29 2017 [antergos is rolling])

### Behavior
* There are some distinctly filament-specific settings in "Printer Settings" that should probably be moved to or overridden by Filament Settings (for example, Hatchbox PET-G seems to compress in the nozzle, then dribbles during travel, then needs a big push to get going again the longer you wait especially on tool change for multi-extruder setups): 
"Length" and "Extra length on restart"  (under "Retraction when tool is disabled...")
(this would be relevant if other extruder uses different filament--which is becoming more common for supports)

(another setting like this is at <https://github.com/alexrj/Slic3r/issues/4211>)

**Comment by lordofhyphens** [comment]
Implemented, but I don't know when they were implemented anymore. See the "Overrides" screen.
