### ISSUE TITLE
Changing "print settings" in the drop down menu is ignoring the layer height when slicing

### ISSUE THREAD

**Issue by mag00-br** [slic3r/Slic3r#4293]
### Version
Slic3r-master.2018.02.08.1593.05461b8.64bit

### Operating system type + version
Windows 10 Home x64

### Behavior
With any model in the screen, I click in preview and it slices the part correctly. Then I go to print setting drop down menu and change to any other configuration.
After that I click in preview again and it slices the model with all new configuration of new print setting but the new layer height. It always use the previous layer height. 
And exporting this slice still maintain the wrong layer height.

As you can see in below image the layer height is with 0.4 mm and the slicing bar shows 0.25 mm (in bottom of image).
![image](https://user-images.githubusercontent.com/30634115/36006340-6d964614-0d23-11e8-9523-50d230eb2975.png)

This issue is occurring in DEV since november 2017 (or even before it).

#### STL/Config (.ZIP) where problem occurs
[polvinho.zip](https://github.com/alexrj/Slic3r/files/1709369/polvinho.zip)

**Comment by platsch** [comment]
I'm unable to reproduce the problem.
What values do you use for Min / Max layer height in the Printer Settings tab? I noticed that this (correctly) limits the layer height but doesn't raise any warning if you set an out of range value
If that's not the reason: could you provide a set of exported configurations for further investigation?

**Comment by mag00-br** [comment]
I've never changed these values.
It's showing 0.15 and 0.30.
I believe that this Min/Max layer configuration is not the problem, because after preview, if I noticed that the layer height is not with the correct value, then I change the value to other one and return it to value that I want and it "correct" the problem.
I've put the exported configurations inside file "polvinho.zip" of original post. Or you need something else?

**Comment by platsch** [comment]
Still unable to reproduce.
What's your OS? Which exact version of Slic3r is affected? I realize that you mentioned the issue is present at least since November 2017 but I'd still like to test the exact same version.
If it is related to a certain OS version, maybe someone else can reproduce the problem.

You are correct, the Min / Max layer height from the extruder settings does not limit the layer heights except for adaptive layer generation or if `z full steps/mm` is used.
@lordofhyphens any opinion on this side-problem? I think it is currently inconsistent, but if we apply the extruder limits for static slicing I expect many people being confused. There should be at least a warning.

You are aware that background processing was disabled in your config? I had to trigger slicing manually after changing the preset.

**Comment by mag00-br** [comment]
My OS is the Windows 10 Home x64.

I'm using development slic3r versions since June of last year (2017).

I've deactivated the background processing since forever.

I've started to notice this issue since November 2017 (or before), so, basically almost every dev version that was available since November 2017 have this issue, and I noticed it from 2 distinct computers, with 2 distinct OS.

The other computer was using Windows 8 Pro x64.

-----------------------------------------------------------------------------------------------------------

Other things that I can add to (maybe) help to reproduce the problem:
- This is my preferences
![image](https://user-images.githubusercontent.com/30634115/36600279-94cd4c78-1890-11e8-8394-c4d13f538f7d.png)

- I use most common parameters on right panels, due to I used to change them constantly. So I've marked the checkbox inside the **Print settings** to them always appear in the screen
![image](https://user-images.githubusercontent.com/30634115/36600510-3faca922-1891-11e8-9882-7d591760d99c.png)

- I've some predefined configurations saved to help me change uncommon settings a bit more quickly.
![image](https://user-images.githubusercontent.com/30634115/36600619-8a555960-1891-11e8-9a23-71a3d66348f3.png)
![image](https://user-images.githubusercontent.com/30634115/36600625-923213c6-1891-11e8-91ba-ed1c10d0bbc6.png)
![image](https://user-images.githubusercontent.com/30634115/36600648-996bcb46-1891-11e8-8476-f034e523eb1f.png)

- All my print settings are forcing all types of extrusion widths be the same width. Doing this, I forcing slic3r to ignore the nozzle width in the **Printer settings**. (This makes me having some problems with bridges and supports, but it's not the point here.)
![image](https://user-images.githubusercontent.com/30634115/36600715-ce659264-1891-11e8-9fc8-4ae1b1a0915b.png)

-----------------------------------------------------------------------------------------------------------

To end all this, I'll print a step-by-step of problem.
- Clear work area
![image](https://user-images.githubusercontent.com/30634115/36600979-aec61e6e-1892-11e8-97fa-3790a84f907e.png)

- Model imported
![image](https://user-images.githubusercontent.com/30634115/36601011-c6dc304c-1892-11e8-825a-b1c5a4e6b66f.png)

- Preview with current settings already loaded (layer height with 0.3 mm)
![image](https://user-images.githubusercontent.com/30634115/36601095-ff98b48c-1892-11e8-9c8a-2b0ff0af6b29.png)

- First layer (0.3 mm as configured)
![image](https://user-images.githubusercontent.com/30634115/36601125-1135213a-1893-11e8-951a-9b0ff0131917.png)

- Second layer (0.6 mm, adding the first to the math) and all others are respecting the 0.3 mm each
![image](https://user-images.githubusercontent.com/30634115/36601159-26e12178-1893-11e8-93a5-f0a1daaac1cc.png)

- Now I've changed the Print settings to other pre configured one, that uses 0.4 mm as layer height
![image](https://user-images.githubusercontent.com/30634115/36601218-5ef839b6-1893-11e8-8d23-8b03255e4c1b.png)

- Clicking in preview it shows the layers
![image](https://user-images.githubusercontent.com/30634115/36601267-79db255e-1893-11e8-861a-6ca1d1908f5e.png)

- Now, the first layer that should be 0.4 mm is with 0.3 mm yet
![image](https://user-images.githubusercontent.com/30634115/36601329-9f28d770-1893-11e8-8551-7b9f5cb4783e.png)

- The second that should be 0.8 mm is with 0.6 mm, and every other layer is with 0.3 mm instead of 0.4 mm as this Print setting is showing in the screen
![image](https://user-images.githubusercontent.com/30634115/36601424-da435948-1893-11e8-98a0-c483a4a25199.png)

---------------------------------------------------------------------------------------------------

So, to make sure that the GCODE be generated correctly I need to change the layer height to another size, and then back to the size I really want to again.

Which brings us to the other problem that I posted too, that making the preview stop working correctly, but this issue have it own topic.

I believe that that's pretty much all the history, but if you need some other information, please ask.

Thanks.

**Comment by mag00-br** [comment]
This issue was solved with correction made in issue #4364.
