### ISSUE TITLE
Feature Request Coasting

### ISSUE THREAD

**Issue by artbody** [slic3r/Slic3r#4362]
In Cura and Simplify .. is a feature named **Coasting**
It means that extrusion is stopped by volume short times before line ends and/or retraction.
![shot_18-04-03_194905](https://user-images.githubusercontent.com/25343071/38266136-25b6a1de-3778-11e8-80f7-108bb56bcba2.jpg)
 So it minimizes stringing

**Comment by lordofhyphens** [comment]
Duplicate of #3014
