### ISSUE TITLE
Use _octoprint._tcp Zeroconf service

### ISSUE THREAD

**Issue by probonopd** [slic3r/Slic3r#4375]
https://github.com/slic3r/Slic3r/blob/19ea7a596a19e7a59ddb2ae2f3dde8c107bd9d11/lib/Slic3r/GUI/PresetEditor.pm#L1326

seems to search for `_http._tcp` services when OctoPrint in fact [advertises itself](https://github.com/foosel/OctoPrint/wiki/Plugin:-Discovery#zeroconf-service-_octoprint_tcp) as `_octoprint._tcp`.

cc @foosel

**Comment by probonopd** [comment]
Currently my instance of [OSMC](https://osmc.tv/) shows up as a 3D printer in Slic3r.

**Comment by lordofhyphens** [comment]
Pull request instead?

**Comment by lordofhyphens** [comment]
@foosel let me know if something is different than the spec and I'll update as necessary.

**Comment by probonopd** [comment]
Thanks, https://github.com/slic3r/Slic3r/commit/c3cb01eb93dd9b078b627acbc77acf526efb4637 addresses this. Works for me.
