### ISSUE TITLE
[Feature Request] Flag bridging moves in verbose GCode comments

### ISSUE THREAD

**Issue by timor** [slic3r/Slic3r#4380]
I would like to be able to see in the generated GCode where bridge moves take place.  This could be used for post-processing scripts.  Or is there a different method of identifying those moves for post processing?

**Comment by lordofhyphens** [comment]
@timor That should be sufficient, although I don't remember offhand if all paths that use bridging flow are marked is_bridge() or just what people usually think of as bridges.

**Comment by timor** [comment]
Thank you very much!
I will try and see if these are the perimeters that I expect.

**Comment by lordofhyphens** [comment]
There's bridging infill too that will show up.

**Comment by lordofhyphens** [comment]
I believe it's treated the same way (because to Slic3r there is no real difference, bridge flow is bridge flow).
