### ISSUE TITLE
Crash when opening printer profile editor

### ISSUE THREAD

**Issue by VanessaE** [slic3r/Slic3r#4384]
### Version

commit df993c5020f36a58184012f2bdf335d82b71711d

### Operating system type + version

Debian 9.3

### Behavior

Start Slic3r, click the gear icon to edit the current printer profile:

```
vanessa@rainbird:~$ Scripts/run-slic3r-alexrj.sh 
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 14: reading configurations from ~/.fonts.conf is deprecated. please move it to /home/vanessa/.config/fontconfig/fonts.conf manually
No use_set_and_wait_extruder in ConfigOptionsGroup config at /home/vanessa/RepRap/Slic3r-alexrj/lib/Slic3r/GUI/OptionsGroup.pm line 374.
```

#### STL/Config (.ZIP) where problem occurs
No STL needed (empty plate)
Config: [slic3r-configs-20180415.ini.zip](https://github.com/slic3r/Slic3r/files/1913089/slic3r-configs-20180415.ini.zip)

**Comment by lordofhyphens** [comment]
That's a new config option, you need to rebuild completely.
