### ISSUE TITLE
2D View shows wrong oriented model

### ISSUE THREAD

**Issue by foreachthing** [slic3r/Slic3r#4439]
### Broken in Version
* Slic3r-master.2018.05.31.1708.ccfb923.64bit
* Slic3r-master.2018.06.05.1711.ff3234d.64bit
* Slic3r-master.2018.06.06.1712.31ba88e.64bit

### Works in Version
* Slic3r-master.2018.05.27.1707.60cce6e.64bit

### Operating system type + version
Win 7 x64

#### 1
* Import [any]-model
* confirm model in 2D-tab (check!)
* back to 3D: rotate model in any other axis than Z
* 2D: model remains the same as before. Bad.
---
#### 2
* 2D: rotate model in Z (45°-button)
* confirmed in 3D! Good!
* 3D: rotate model BACK (in Z -45°)
* 2D confirmed. Good
---
#### 3
* 2D: Rotate model 90° in X
* 2D: model not updated! BAD!
* 3D: model good.
---
#### 4
* 3D: Rotate model 90° in X then 45° in Z.
* 2D shows the original imported model, only rotated 45° in Z ...
---

2D is somehow out of sync. Whatever is in 3D, is in Preview and Layers as well.

Some screenshots from the SAME oriented model. Cycling through the tabs:

![image](https://user-images.githubusercontent.com/10420187/41037553-f1a16f0c-6993-11e8-868a-1c2403a282f4.png)

Wooohaaa!
![image](https://user-images.githubusercontent.com/10420187/41037562-f691d1d2-6993-11e8-89d4-b20644b436e0.png)

![image](https://user-images.githubusercontent.com/10420187/41037590-063f9b28-6994-11e8-989a-ac2a98d9db99.png)

![image](https://user-images.githubusercontent.com/10420187/41037611-0cff4b52-6994-11e8-810a-2bcd30719616.png)

#### STL/Config (.ZIP) where problem occurs
Use your favorite model and fastest slicing profile.

**Comment by Oekn5w** [comment]
Cause:

https://github.com/slic3r/Slic3r/blob/1527cfbb26b8494c10a7868f36510aaa1768a43b/lib/Slic3r/GUI/Plater.pm#L2644-L2650

return condition is true except the initial loading of the object, although the variable isn't used anywhere else except the declaration?!
Threading issue?

@TheThirdOne, you seem to have added this a week ago?

**Comment by TheThirdOne** [comment]
Ok, this came from my misunderstanding of how perl threading works. `plater_object` gets copied which means that resetting in the other thread does not have an effect. Moving the reset to `on_thumbnail_made` works as intended.

@foreachthing, in case you were wondering, the reason Z rotations don't exhibit the bug is that the thumbnail is not retaken on Z rotations. It can just be rotated.

**Comment by foreachthing** [comment]
Another issue with 2D:

3D: 
![image](https://user-images.githubusercontent.com/10420187/41355014-ba0ff1b6-6f20-11e8-8e17-464d61fbd220.png)

2D:
![image](https://user-images.githubusercontent.com/10420187/41355023-beb796ba-6f20-11e8-93dd-833083094f85.png)

Model:
[Gear_Pump.zip](https://github.com/slic3r/Slic3r/files/2098340/Gear_Pump.zip)

**Comment by lordofhyphens** [comment]
@foreachthing please open a second issue for the other problem.
