### ISSUE TITLE
Maximum Filament Extruder Width Increase Request

### ISSUE THREAD

**Issue by LandSquidConfirmed** [slic3r/Slic3r#4440]
Slic3r 1.3.1

Discovered Problem on Windows 10, probably present on MacOS and Linux

For large 3D printers, the maximum extrusion width of 1.7mm is prohibiting. (This is a problem for at least me personally with a 3mm nozzle) Because this seems like an arbitrary limit, I was wondering if there was some way to change it by editing Slic3r files, and hoping that it could be changed by default.

Providing support for extremely large printers would be great in Slic3r, because no other software seems to be able to pull off slicing for large printers without many issues. 

This is the error that is printed when I try to export or save a configuration file.
![extrusion width error](https://user-images.githubusercontent.com/28678017/41071972-fb57daf6-69c8-11e8-85ee-485243e03058.PNG)

These are the settings for the extruder that is configured to be using.
![extruder 2 settings](https://user-images.githubusercontent.com/28678017/41072046-67c84a9a-69c9-11e8-93af-94a463e7e571.PNG)

These are the extrusion width settings.
![extrusion width settings](https://user-images.githubusercontent.com/28678017/41072102-b9dadf0a-69c9-11e8-9653-1e19334d2a5c.PNG)

I am currently testing with this STL file.
[Test Print.stl.zip](https://github.com/slic3r/Slic3r/files/2078572/Test.Print.stl.zip)

Any help is greatly appreciated!

**Comment by lordofhyphens** [comment]
@LandSquidConfirmed Are you talking about the automatic width calculation or what you set via a config parameter?

**Comment by lordofhyphens** [comment]
@LandSquidConfirmed Please include a Slic3r config export (ctrl-E) and a 3D model with which you are seeing the issue.

**Comment by LandSquidConfirmed** [comment]
I updated the post, hopefully this will help you reproduce the issue.

**Comment by lordofhyphens** [comment]
@LandSquidConfirmed I need an exported config, not screenshots. See the highlighted menu option in the screencap below:
![image](https://user-images.githubusercontent.com/31754/41074290-029adc42-69cd-11e8-920a-349fde6d4049.png)

Reference: https://github.com/slic3r/Slic3r/blob/master/.github/CONTRIBUTING.md

**Comment by lordofhyphens** [comment]
@LandSquidConfirmed So the error you are seeing comes from Config.pm around 276. It triggers when you try to have an extrusion width 10x the nozzle width. You can, of course, delete the validation check (doesn't need recompilation).

**Comment by LandSquidConfirmed** [comment]
Thanks buddy mistakes were made.
