### ISSUE TITLE
Starting on Slic3r development - IDE and configuration

### ISSUE THREAD

**Issue by Annaf12** [slic3r/Slic3r#4442]
Hello Slic3r folks,
I'm a student at a technical university in germany. In my upcoming project I want to get involved with Slic3r development with the ultimate goal of writing own plugins.
As I didn't find any hints on the project sites, in the repo or the web:
What IDE do you recommend or are you using for this? Eclipse/QtCreator/...? Can you provide me with a project configuration for it?
And are there any hints on getting started?
Thanks a lot and best regards,
Annaf12

**Comment by lordofhyphens** [comment]
The best hint I have to getting started is to read over the Low Effort tagged issues and understanding what is requested. Gain experience understanding people's issues and build out from there.

Slic3r doesn't have/use a plugin system. The closest we have is post-processing scripts (see #3750 for some thoughts about embedding something to internalize some scripts) and modifier meshes.

I don't use an IDE. As such, I don't have one to recommend (nor can I help you get one set up). 

- [Task ideas](https://github.com/slic3r/Slic3r/wiki/TODO)
- [General information](https://github.com/slic3r/Slic3r/wiki/Documentation) - includes build instructions
- https://github.com/slic3r/Slic3r/wiki
