### ISSUE TITLE
Feature Request: Perimeter Overlap (Like Infill/perimeter, but between perimeters only)

### ISSUE THREAD

**Issue by KevinPezz** [slic3r/Slic3r#4449]
### Version
1.39.2+

I have been tuning my extrusion multiplier via wall thicknesses and noticed the perimeters arent affected by infill/perimeter overlap. my extrusion width is tuned to just over .4mm (.41mm avg for preventing any underextrusion) via single-walled cube tests. And yes I have my extrusion widths set to .4mm, not .45mm. 

Now when I print a double-walled cube test, the shell measures out to .775mm avg. Should be near .80mm (again, not trying to induce any underextrusion). Now of course, people would say, "just make the extruder multiplier greater". But then we're not getting the extrusion widths accurate, the whole print will be over-extruded, and the overlap over the course of adding more perimeters (say 10 perimeters for 4mm shells) will get overextruder more and more.

On a side note, I've been experimenting how to reach dimensional accuracy and precision recently. I also developed a formula a while ago to optimize scale (originally done via e-steps) and xy comp. It made for an odd behavior, with partly perfect results. 
>The 20mm cube with 10mm hole came out 20 +/-.01mm and 10mm +/-.02mm (not including the z-seam). 
>The 100mm prism with 50mm hole came out 100 +/-.01mm and _45 +/- 1mm_ (if I remember correctly).  

I feel this may be a small but forward step in getting more "blueprint" prints...

**Comment by lordofhyphens** [comment]
Reproduce on Slic3r 1.3.0 or 1.3.1-dev, not Prusa3d fork.
Provide config export and some pictorial evidence--screenshot from Slic3r's 3D preview helps.

1.3.0 https://github.com/slic3r/Slic3r/releases/tag/1.3.0
1.3.1-dev https://dl.slic3r.org/dev

I will reopen then.

Infill/Perimeter overlap is designed to help promote bonding between the two.
