### ISSUE TITLE
Unable to run Slic3r on Ubuntu 18.04 LTS fresh install

### ISSUE THREAD

**Issue by Diaoul** [slic3r/Slic3r#4450]
### Version
Slic3r-master-latest.AppImage | 2018-06-09 05:08 | 24M

### Operating system type + version
Ubuntu 18.04 LTS fresh install

### Behavior
* Unable to run Slic3r

```
> ./Slic3r 
Gtk-Message: 01:19:29.613: Failed to load module "canberra-gtk-module"
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
The program 'slic3r.pl' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 1972 error_code 2 request_code 152 minor_code 24)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

I've tried installing `canberra-gtk-module` and `freeglut3` but I have the same error (except the missing on the gtk module).

**Comment by Diaoul** [comment]
That was it. I installed proprietary NVIDIA drivers instead of the default open ones and it worked. Thank you!

**Comment by yeckel** [comment]
For the case someone reads this issue as a new problem on Ubuntu 20.04. I've solved it by using the slic3r from the official Ubuntu repository (apt install slic3r) and this works. Even the configuration is there. The AppImage does not.
