### ISSUE TITLE
Move Extruder Clearance and Height to Printer Settings

### ISSUE THREAD

**Issue by teapot3d** [slic3r/Slic3r#4455]
### Version
Prusa 1.39.2 + win64

In the present version, the extruder clearance parameters are included in the Sequential Printing group in the Output Options chapter of the Print Settings tab.  

I believe it is correct for the "Complete individual objects" checkbox to be under the Print Settings tab but I think the associated Extruder clearance Radius and Height should be properties of the printer - somewhere under the Printer Settings tab.

It may be desirable to echo these dimensions, as read-only, in the present position along with a note to the effect of "to adjust extruder clearance, see Printer Settings tab."

**Comment by lordofhyphens** [comment]
Please confirm that this is necessary/desirable on 1.3.0 https://github.com/slic3r/Slic3r/releases/tag/1.3.0 and update your post accordingly.

I will reopen then.
