### ISSUE TITLE
Minor typo in hints

### ISSUE THREAD

**Issue by ClusterM** [slic3r/Slic3r#4461]
### Version
1.3.1-dev

In print settings -> infill settings -> fill density:
![image](https://user-images.githubusercontent.com/4236181/41802559-42c0ec3e-768a-11e8-8f04-e4d9a641c051.png)
default: 20%

But in shortcuts:
![image](https://user-images.githubusercontent.com/4236181/41802591-7ccda32c-768a-11e8-942b-5c932468437d.png)
default: 50%

**Comment by lordofhyphens** [comment]
It's not a typo. The default value on the Print Settings page is referring to the default-default value (that is, the default value hardcoded). Shortcut is referring to what you changed it to in Print Settings (that is, the current default for that preset).
