### ISSUE TITLE
Broken part in the model when loading stl file by slic3r

### ISSUE THREAD

**Issue by shushengyu** [slic3r/Slic3r#4463]
### Version
1.2.9
### Operating system type + version
win10

### Behavior
     Using slic3r import a stl file, there is a broken part in the model, and resulted some empty sliced layer.
     But in other 3d model viewer software, there is not the broken part.
     The first picture was produced by slice3r, and the other was produced by 3d-tool.

![1](https://user-images.githubusercontent.com/28980232/41897061-dd3c9666-7958-11e8-8ce5-0ef6e01eecbe.jpg)
![2](https://user-images.githubusercontent.com/28980232/41897074-e47f8c30-7958-11e8-8743-4f8809f83cf9.jpg)

The .slt file is too large to upload,about 35MB.

**Comment by lordofhyphens** [comment]
Run the model through service.netfabb.com 

Slic3r is not going to try to be prescient and fix everything.

**Comment by shushengyu** [comment]
thank you!
