### ISSUE TITLE
Thin wall : improvements

### ISSUE THREAD

**Issue by supermerill** [slic3r/Slic3r#4469]
Hi,
I just slain my personal dragon by improving the thin wall algorithm.

 * no more strange turn at end => fusion of voronoi end lines when they are near enough
 * anchoring inside the perimeters => extends the lines end inside the perimeter to join it. A gui parameter can be created to adjust it if needed (currently, it extends to meet the center).
 * conservation of too small segments of thin walls when they are crossing each other => modification of the fusion algorithm to select the most strait path instead of a random one
 * no more cutting of small walls path by the gcode writer (no_sort for each thin wall extrusion) to have nice long lines of extrusions instead of many smaller.

before:
![smallwall_problem](https://user-images.githubusercontent.com/6536403/42289796-c6c73f8e-7fc1-11e8-81bd-ad378f6f8eca.png)
![thin_wall_bad](https://user-images.githubusercontent.com/6536403/42289984-fc99e8c2-7fc2-11e8-9d8a-b4672bf2b5fb.png)

after:
![thin_wall_happy](https://user-images.githubusercontent.com/6536403/42289798-cda01e98-7fc1-11e8-8236-853c827ddc1d.png)
![thin_wall_success](https://user-images.githubusercontent.com/6536403/42289997-ff9120a4-7fc2-11e8-96c6-f5626ede6d21.png)

My problem: Last time i tried to merge my code in alexrj branch, it was a chore for me (bad at perl and enormous time for compiling)

But perimeterGenerator.cpp and ExPolygon.cpp seems close enough to create a pull request for a sub-part of my modifications (point 1->3). For the "no more cutting of small walls path by the gcode writer", i won't translate my c++ code into the perl codebase (that's why I didn't submit a pull request for my ironing code).

What do you think?

#3709 #3509

for the curious: f6854427eb8ab44c3beddda2dc5386c73cda08e3

**Comment by lordofhyphens** [comment]
@supermerill if you don't want to port your C++ ironing code to perl, submit a PR for just the C++ portion and I'll cook up an XS so it can be called from the perl section. Or port more of gcode to C++ :)

**Comment by lordofhyphens** [comment]
As for compiling, there's a trick you can do so long as you're done changing stuff in libslic3r.h:

On Linux or OSX: 
`eval $(/path/to/perl -Mlocal::lib=/path/to/slic3r/local-lib)`

On Windows Powershell:
`Invoke-Expression "$(perl -Mlocal::lib=/path/to/slic3r/local-lib)"`

Either command will set up things in that CLI window so you can just cd to xs and run `perl Build.PL` and `./Build install`. That will just build the XS/C++ part.

I am de-Perling Slic3r as fast as I can manage.

**Comment by supermerill** [comment]
Thanks, i will try.

**Comment by lordofhyphens** [comment]
@supermerill I'll be on IRC quite a bit over the next few days (including today) if you want to chat in realtime about it. I'd love to get your code into Slic3r.

**Comment by lordofhyphens** [comment]
Merged, thank you for the work @supermerill.
