### ISSUE TITLE
Aditions list

### ISSUE THREAD

**Issue by Tinchus2009** [slic3r/Slic3r#4474]
Sorry to post here but coulnd find the info: how can we know wich changes has been added in each of the automated fresh builds

When building from source we can know it doing a git log command but in the already builted releases how can we know it?

**Comment by lordofhyphens** [comment]
Every build is tagged with the commit it came from.


Slic3r-master.2018.07.06.1734.b3d3bed.64bit.zip

b3d3bed is the short hash. 

Compare against https://github.com/slic3r/Slic3r/commits/master

**Comment by Tinchus2009** [comment]
sorry
