### ISSUE TITLE
Crash when changing presets while current preset is modified but unsaved

### ISSUE THREAD

**Issue by dwillmore** [slic3r/Slic3r#4477]
### Version
Current master branch as of 20180709 but has been in there for months.
Specifically: 1.3.0-23-gb3d3bed8

### Operating system type + version
Fedora F27 current as of 2018/07/09

### Behavior
Start with a fresh invocation of the Slic3r GUI.
1. Add a model--doesn't seem to care what it is
1. Change a setting under a Print Setting, Printer Settings, or Filament Settings
1. Without saving the preset (which will be marked as "(modified)"), try to change to a different preset of that type
1. crash :
````Can't locate object method "SetYesNoCancelLabels" via package "Wx::MessageDialog" at /path/to/slic3r/Slic3r/lib/Slic3r/GUI/Preset.pm line 91.````

_Is this a new feature request?_
Nope, unless this is the desired behavior. :)

#### STL/Config (.ZIP) where problem occurs
I can add this if it doesn't reproduce with a default environment.

**Comment by lordofhyphens** [comment]
Does work with AppImage build:

Expected behavior: MessageDialog popup 
![image](https://user-images.githubusercontent.com/31754/42470694-daf3dc52-8380-11e8-9d22-0fcd1eda854d.png)

**Comment by dwillmore** [comment]
The appimage does provide that prompt.  Must be system dependent.  Removing system provided perl-wx and rebuilding with Slic3r provided/installed one.

**Comment by lordofhyphens** [comment]
Closing as was related to individual build environment.
