### ISSUE TITLE
Q: acceleration issue with non prusa printer

### ISSUE THREAD

**Issue by boelle** [slic3r/Slic3r#4492]
### Version
1.41.0-alpha2+win64

### Operating system type + version
win10

### Behavior
* _Describe the problem_

i used to use version 1.39.2 and was very happy with it

i use it together witn my mendel90 and marlin bugfix 2.0.x with the same feedrate, acceleration and jerk settings as for a mk2s taken from here: https://github.com/prusa3d/Prusa-Firmware/blob/MK3/Firmware/variants/1_75mm_MK25-RAMBo13a-E3Dv6full.h 
and here: https://github.com/prusa3d/Prusa-Firmware/blob/MK3/Firmware/Configuration.h

then the youtuber cnc kitchen showed the gyroid infill and i found out that i have to update, no big deal i thought, but i was wrong

in version 1.39.2 i pretty much just copied the settings etc for the Mk2s and changed the start gcode, that was it

but in 1.41 in the gcode it adds a section in the start with feedrates etc and then every now and then a progress code

now my printer skips steps (at least during non print moves) because it moves to fast and i just cant figure how to get rid of that section in the start. i filled in the machine limits with just zero but then it moves so slow i cant see it moves

i even tried to create a custom setup from scratch but the same thing happend

any pinters or suggestions are welcome... and yes i know i dont have a prusa printer but it like the software :-/

**Comment by xoan** [comment]
You are in the wrong place: if you use the Pruesa Edition of Slic3r, you should report issues in https://github.com/prusa3d/Slic3r

**Comment by boelle** [comment]
upppps

let me copy over the issue first and then i will close it

my mistake... blind old man here :-(

**Comment by lordofhyphens** [comment]
@boelle if you can reproduce with a build from https://dl.slic3r.org/dev/ I can also take a look at this.

**Comment by lordofhyphens** [comment]
1.3.1-dev has the gyroid infill too :)

**Comment by boelle** [comment]
hmm... the tabs do not show up and each time i click on a menu i get the spinning wheel and "not responding" in the title bar

i do run the latest of win10 64 bit (danish)

**Comment by lordofhyphens** [comment]
Open a profile to edit.

You may want to go to File->Preferences and change the editor mode to tabs

**Comment by boelle** [comment]
but that assumes i can get to the menu

all i get is the spinning wheel and the "not responding" in the title bar

**Comment by boelle** [comment]
![image](https://user-images.githubusercontent.com/3832239/43363573-e3901010-9307-11e8-893d-b37f87a41b0e.png)

**Comment by boelle** [comment]
like this:
![image](https://user-images.githubusercontent.com/3832239/43363583-2601a454-9308-11e8-9ce8-55eba81a7429.png)

**Comment by lordofhyphens** [comment]
Click on the gear icon next to the drop down.

**Comment by boelle** [comment]
can you explain why i get the wheel icon so much and i also see a lot of "not responding" ?

**Comment by lordofhyphens** [comment]
I don't know currently. Compare with 1.3.0 (see https://github.com/slic3r/Slic3r/releases/tag/1.3.0 )

**Comment by boelle** [comment]
oh well, maybe the next version runs better, i thought there was some windows stuff that was missing
