### ISSUE TITLE
Slic3r snapshot downloads broken (server is full, so upload fails).

### ISSUE THREAD

**Issue by mag00-br** [slic3r/Slic3r#4499]
The new links for automated development builds are all with 0 kb.

**Comment by lordofhyphens** [comment]
I'll have to sort it out tonight; thanks for the heads-up.

**Comment by lordofhyphens** [comment]
@mag00-br builds are available again.

**Comment by lordofhyphens** [comment]
@alexrj the drive space seems to be taken up by something else that isn't in the folder.

**Comment by scott0122** [comment]
Slic3r dev build downloads still not working.

**Comment by lordofhyphens** [comment]
@scott0122 Out of space; @alexrj has to sort out the server (I do not have sufficient access rights).

**Comment by lordofhyphens** [comment]
I have kicked off builds and the space situation should have been resolved. 

Check in about an hour.

**Comment by lordofhyphens** [comment]
Windows and OSX builds look fine. Something looked off about the Linux build sizes, so I will look at that later.

**Comment by lordofhyphens** [comment]
There's the Linux build (broken for unrelated reasons). Closing.
