### ISSUE TITLE
Windows snapshot download broken

### ISSUE THREAD

**Issue by adras** [slic3r/Slic3r#4501]
### Version
Does not apply

### Operating system type + version
Windows

### Behavior
Slic3r dev build downloads not working. Size of files available for download is 0 and files have a .zip.filepart extension. See: http://dl.slic3r.org/dev/win/

Therefore, I can't download a recent snapshot :(

**Comment by lordofhyphens** [comment]
Duplicate of #4499.

Snapshot should be available in an hour.

**Comment by scott0122** [comment]
Slic3r dev build downloads still not working.

**Comment by lordofhyphens** [comment]
Locking to collect reports into #4499
