### ISSUE TITLE
[BUG] Alert windows when using print modifier

### ISSUE THREAD

**Issue by macsddau** [slic3r/Slic3r#4503]
### Version
1.2.9

### Operating system type + version
Mac OS 10.13.6

### Behavior
About 150 alert windows when using print modifier.

#### STL/Config (.ZIP) where problem occurs
[[BUG] Alert windows when using print modifier.zip](https://github.com/slic3r/Slic3r/files/2260554/BUG.Alert.windows.when.using.print.modifier.zip)

**Comment by lordofhyphens** [comment]
Screenshot would be nice.

Also, grab a copy of 1.3.0.

https://github.com/slic3r/Slic3r/releases/tag/1.3.0

**Comment by macsddau** [comment]
Very nice with 1.3.0, no more alert window.

Thanks a lot !

![capture d ecran 2018-08-05 a 21 09 46](https://user-images.githubusercontent.com/42119830/43689029-0f16fbb2-98f4-11e8-8793-f5528aa8c19a.png)
