### ISSUE TITLE
slic3r infills a hole

### ISSUE THREAD

**Issue by l29ah** [slic3r/Slic3r#4531]
### Version
880e9a52c34943ba4ee22a3d6c2162d314af4e66

### Operating system type + version
Gentoo GNU/Linux

### Behavior
![](https://a.doko.moe/jalaon.png)
![](https://my.mixtape.moe/vsoppx.png)

#### STL/Config (.ZIP) where problem occurs
[bug.zip](https://github.com/slic3r/Slic3r/files/2354532/bug.zip)

**Comment by foreachthing** [comment]
Use https://service.netfabb.com/service.php with your stl and you're all set.
![image](https://user-images.githubusercontent.com/10420187/45152897-9ec8ac00-b1d2-11e8-8015-4d061597ce0f.png)
Left: the fixed stl. Right: your original.

**Comment by l29ah** [comment]
Interesting. Calling `admesh` on it doesn't fix it.

**Comment by lordofhyphens** [comment]
If admesh could fix it, slic3r wouldn't show any issues.

**Comment by l29ah** [comment]
But i don't have any horizontal surfaces there.

**Comment by l29ah** [comment]
Is there a solution that doesn't involve using magic web services?

**Comment by lordofhyphens** [comment]
You can probably spot the issue with either mesh lab or the application version of netfabb.

**Comment by l29ah** [comment]
On Fri, Sep 07, 2018 at 12:08:47PM -0700, Joseph Lenox wrote:
> You can probably spot the issue with either mesh lab or the application version of netfabb.

meshlab opens it just fine.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by l29ah** [comment]
![](https://a.doko.moe/ibeaxk.png) does this look bad?

By the way, the model comes from openscad, and i wasn't doing anything nasty with polygons, just subtracting primitives and hulls. Even the preview looks fine.

> manually

uhh

**Comment by foreachthing** [comment]
Yes it does look bad!
Non manifold edges .. 54; I've seen worse!
Zero faces: 2209! WOW!
Intersecting faces: 484 .... baah!

Manually or use some magic service ;-)
In Blender it has a "make manifold" button. Also, if you enter the edit mode, while the part is selected (press TAB after "check all"), then you get more tools to fix the mesh.

**Comment by foreachthing** [comment]
Maybe tweak the settings in openscad ... reduce or increase tessellation until you get a good model.
