### ISSUE TITLE
SLIC3R_VERSION should be set to `git describe --tag` during building

### ISSUE THREAD

**Issue by l29ah** [slic3r/Slic3r#4532]
Otherwise it's cumbersome to find out the exact commit the binary came from.
Apparently just `sed`'ing `xs/src/libslic3r/libslic3r.h` will do the job.

**Comment by lordofhyphens** [comment]
There is a second variable available for the build commit and it is
populated in the c++ build path.

**Comment by lordofhyphens** [comment]
Done.

**Comment by lordofhyphens** [comment]
If you are building yourself, you will need to set SLIC3R_GIT_VERSION as an environment variable prior to running `perl Build.PL`.
