### ISSUE TITLE
Missing/disappearing preset profiles for print settings

### ISSUE THREAD

**Issue by haleypearse** [slic3r/Slic3r#4563]
### Version
slic3r PE 1.41.1-rc+
(3.4.1 hex file firmware MK3 variant with [#1193](https://github.com/prusa3d/Prusa-Firmware/pull/1193) merged)
https://github.com/prusa3d/Prusa-Firmware/files/2456589/Prusa-Firmware-3.4.1-fan-changes.zip

### Operating system type + version
Mac OS 10.14 Mojave

### Behavior

Every time I load slic3r or change printer profile I have to redo all my print settings, because the presets do not show. If I save a preset, it will show, but none others. Occasionally they will all come back temporarily. Specifically, print settings reset to slic3r defaults with no presets available. I get a message saying my 0.3mm nozzle can't be narrower than the layer height, signalling to me that it's time to enter all the settings again. 

![image](https://user-images.githubusercontent.com/10296672/46821378-56eef480-cd3d-11e8-9d21-3e064d284d5b.png)

**Comment by lordofhyphens** [comment]
https://github.com/slic3r/Slic3r/releases/download/1.3.0/slic3r-1.3.0.dmg

I will reopen if you can reproduce with that version.

**Comment by haleypearse** [comment]
Solved! It seems this was simpler than I'd thought. "Show incompatible print and filament presets" was unchecked, which seems to have been the problem. 
![image](https://user-images.githubusercontent.com/10296672/47727972-adec3900-dc1a-11e8-9400-e9fb5607dcc7.png)

**Comment by lordofhyphens** [comment]
I like it when it's a simple thing.
