### ISSUE TITLE
Slic3r 1.3 does not open on macOS 10.12.5

### ISSUE THREAD

**Issue by ganzocrypt** [slic3r/Slic3r#4564]
Slic3r 1.3 does not open on macOS 10.12.5.

When launched it appears the window vault of verifying application and it sits there and does not go on.

**Comment by lordofhyphens** [comment]
I wonder if Apple has decided to pull all opengl support officially from 10.12.5?

**Comment by lordofhyphens** [comment]
I don't have 10.15 to test myself, unfortunately. 

If it's dying on the signed check that shouldn't be happening as @alexrj did get dev keys and the app should be signed. 

Could you try a build from https://dl.slic3r.org/dev/mac/ ?

**Comment by ganzocrypt** [comment]
well, it's not dying, it just sits there.
I do not have the environment ready to do a build.
If no one reported must be something with my mac? not sure

**Comment by lordofhyphens** [comment]
@ganzocrypt sorry, I just derped up and misread 10.12.5 as 10.15. AFAIK it should be working and this is the first report I've seen. I will test on my own system (on 10.14 High Sierra) tonight.

**Comment by honza-kasik** [comment]
I have 10.13.16 and this appears when I try to open downloaded app: ![](https://i.postimg.cc/kgpNFFC7/Screen-Shot-2018-10-17-at-20-51-39.png)

**Comment by lordofhyphens** [comment]
@alexrj anything up with your key?

**Comment by lordofhyphens** [comment]
hrm, OSX itself reports that it thinks the code has been modified from the signed version. That's weird to me because I don't recall messing with the build system. Now I just have to remember the URL for the build bot.

**Comment by lordofhyphens** [comment]
So I've signed the dmg as well but forgot to do more testing. I'll get to it tonight. @ganzocrypt any improvement?

**Comment by ganzocrypt** [comment]
I do not have an env to do the build so cannot help on that side, but willing to test the dmg as soon as you build it, just ping me.

**Comment by lordofhyphens** [comment]
@ganzocrypt it should be up already. https://dl.slic3r.org/dev/mac/slic3r-1.3.1-dev-f487129.dmg

**Comment by lordofhyphens** [comment]
@ganzocrypt you wouldn't be able to help with a build environment, unfortunately. It looks like it's Gatekeeper blocking execution.

**Comment by ganzocrypt** [comment]
no luck.
it shows the window "Verifying Slic3r" .... and it sits there !

**Comment by lordofhyphens** [comment]
Note: close this when #4576 closes.

**Comment by lordofhyphens** [comment]
@ganzocrypt try it now.

**Comment by ganzocrypt** [comment]
which one?

**Comment by lordofhyphens** [comment]
master-latest

**Comment by ganzocrypt** [comment]
yes it works!
thx
