### ISSUE TITLE
Incapable of slicing properly for thin models.

### ISSUE THREAD

**Issue by TaiTair** [slic3r/Slic3r#4570]
**Describe the bug**
Slic3r incapable of filling properly with thin models.

**To Reproduce**
1. Use the stl provided in this report.
2. Slice it with nozzle width of 0.4mm, layer height of 0.15mm and first layer height of 0.20mm. 
Keep detect thin walls off as it makes things even worse.
2 Perimeters and 3 solid layers.  Infill at 20% rectilinear.
Use first layer extrusion width of 200%, top solid infill of 150% and infill/perimeters overlap of 30%.
All other settings not important for this test.
3. See how the model slices incorrectly.

**3D Model and Slic3r Configuration Export**
[bugresources.zip](https://github.com/slic3r/Slic3r/files/2527006/bugresources.zip)

**Expected behavior**
I expected it to fill properly without any gaps.

**Screenshots**
Noticeable gaps in infill, straight lines and not enough layers:
![image](https://user-images.githubusercontent.com/8822568/47679181-daec0d80-db80-11e8-9ec7-1849321c9550.png)
In comparison, sliced with curaengine, it looks how it should look:
![image](https://user-images.githubusercontent.com/8822568/47679256-14bd1400-db81-11e8-93bb-40aed65c18aa.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 1.2.9

**Comment by supermerill** [comment]
the  1.2.9 is 3 years old.
at least, can you try with the 1.3? It's only 5 month old.

also

> I expected it to fill properly

It's a bit light as a description. Point the problematic area in the picture, and explain why it's bad.

**Comment by TaiTair** [comment]
> the 1.2.9 is 3 years old.
> at least, can you try with the 1.3? It's only 5 month old.
> 
> also
> 
> > I expected it to fill properly
> 
> It's a bit light as a description. Point the problematic area in the picture, and explain why it's bad.

Are you blind or are you just trying to be annoying? Use your eyes, the gaps in the infill are clearly visible without even zooming in the pictures. Also the infill is a lot lighter and not a good representation of the model, whereas cura makes an accurate representation of the model. Slic3r makes an incomplete, flimsy model.

Here I downloaded this one: https://dl.slic3r.org/dev/linux/Slic3r-master-latest.tar.bz2 and it wouldn't even launch due to perl errors and a misconfiguration of local libs.

![image](https://user-images.githubusercontent.com/8822568/47686617-55288c00-db99-11e8-808c-ac6e83144915.png)

I don't have the time to test the release packages and make them work. If I wanted to compile I'd grab the source. When I download a pre-compiled "release" package I expect it to work without confusion.
Wish I could test the 1.3.

**Comment by lordofhyphens** [comment]
@TaiTair Use the AppImage.

Which of the settings from the bundle were you testing with (the Ctrl-E export is asked for to avoid this question).

**Comment by lordofhyphens** [comment]
I took a guess from the bundle (all three "My Settings.ini") and produced [4570.zip](https://github.com/slic3r/Slic3r/files/2527514/4570.zip)
Here's the slice from the top with 1.3.1-dev:
![image](https://user-images.githubusercontent.com/31754/47687902-98422980-dbb0-11e8-8b8d-2a11f180f368.png)

I originally thought you were complaining about the tail section, so I had zoomed in on those. 

0.65:
![image](https://user-images.githubusercontent.com/31754/47687796-0f2af280-dbb0-11e8-9bad-fe813cc2d29c.png)

1.25:
![image](https://user-images.githubusercontent.com/31754/47687806-2669e000-dbb0-11e8-9a8e-0f5abbe438f5.png)

3.05:
![image](https://user-images.githubusercontent.com/31754/47687827-3aaddd00-dbb0-11e8-8a85-54b4ec81f72f.png)

**Comment by lordofhyphens** [comment]
@TaiTair Odd, on my Debian Sid system the tar.bz2 starts right up when calling ./Slic3r. 

Something's up with the AppImage on my system (that I just noticed) when downloading it as a check. Looking into it now.

**Comment by TaiTair** [comment]
@lordofhyphens Thanks for your help.
I tested the AppImage and the result was much better - comparable to cura's result:
![image](https://user-images.githubusercontent.com/8822568/47728885-6f577e00-dc1c-11e8-9d74-6992a0fe330e.png)

So the incorrect slicing seems to be solved with the latest versions. Now the next question is how do I get the tar.bz2 to work? I'd like to embed it in my distro so it can be called from repetier-host. Going to try building it from source.

**Comment by TaiTair** [comment]
Ok I managed to compile 1.3.1-dev without issues and to use it.
The problem is mostly gone and "Detect thin walls" works better. I tweaked it a bit and managed to get rid of gaps on the top of the model.
That being said I still got a very annoying gap under the model. Which settings should I try changing? What am I doing wrong?

![image](https://user-images.githubusercontent.com/8822568/47731981-8305e300-dc22-11e8-862e-4bf6801c5fdc.png)

[config.txt](https://github.com/slic3r/Slic3r/files/2530440/config.txt)

**Comment by TaiTair** [comment]
First layer view, very noticeable gap:
![image](https://user-images.githubusercontent.com/8822568/47732387-530b0f80-dc23-11e8-9bf8-347f09476a54.png)

**Comment by TaiTair** [comment]
Yeah... No matter what I do the sliced model has gaps.

**Comment by TaiTair** [comment]
Looks like the logic for slic3r is flawed. The paths in Cura look way more logical. Slic3r on the left, cura on the right. Layer height settings are exactly the same.
![image](https://user-images.githubusercontent.com/8822568/47743089-6e821480-dc3b-11e8-98a0-f82a494f5d42.png)

**Comment by TaiTair** [comment]
@lordofhyphens Could you look at your first layer and check for any gaps?
Even with the AppImage I get gaps in my slices - whereas yours looks perfect. I have a feeling maybe some of my dependencies are glitching out?

**Comment by lordofhyphens** [comment]
@TaiTair Yeah, I can take a look at it when I get some time tonight. I had used your three profiles labeled "My Settings" to generate my own screencaps. 

Using Slic3r's own preview with the AppImage would give what Slic3r thinks the paths look like. You also can take a look at Slic3r's own host mode :)

With the tar.bz2, you'd tell rephost to call the Slic3r script that's in the dir.

**Comment by TaiTair** [comment]
Yeah so I tried running it on my Windows partition and the slicing was pretty much flawless. No gaps or anything. Which tells me something might be wrong with my Ubuntu.

Very interesting. So I tried slicing it directly from slic3r and looking at the preview inside of slic3r's gui and it seemed flawless too:

![image](https://user-images.githubusercontent.com/8822568/47762425-eb33e380-dc79-11e8-8962-11073d3251ed.png)

Now I'm at a loss because it seems like the problem is inside Repetier-host. I'm pretty sure i've seen those gaps in my prints. Is it possible repetier is messing things up?
Loaded the g-code from slic3r into repetier again (sliced directly with slic3r and then launched repetier separately)
Again some gaps on almost every layer.

![image](https://user-images.githubusercontent.com/8822568/47762574-7e6d1900-dc7a-11e8-9e05-248544b1ae53.png)

What's going on??

**Comment by lordofhyphens** [comment]
Have you tried to print it?

**Comment by TaiTair** [comment]
Yeah gcode.ws not showing me any gaps with this:

[F-47 Mini .gcode.txt](https://github.com/slic3r/Slic3r/files/2535828/F-47.Mini.gcode.txt)

Had to .txt it because Github doesn't take .gcode for attachements.

**Comment by lordofhyphens** [comment]
@TaiTair it does take .zip though :) 

If Gcode.ws doesn't think there is something missing, and Slic3r doesn't think there should be something missing, then I'd try to print it.

**Comment by TaiTair** [comment]
Alright I'll try soon as I get back from work.

**Comment by TaiTair** [comment]
Little bit of digging around:

Seems like the cause for my problem is actually Repetier-host and I have the feeling it actually prints the problem (I'll double check tonight):
https://forum.repetier.com/discussion/4905/gaps-between-layers-in-print-preview

Here's a preference menu inside Repetier that needs to be setup for previews to work correctly. I have yet to set it up properly.

![image](https://user-images.githubusercontent.com/8822568/47823434-8b931200-dd25-11e8-99a9-78a8a6936aae.png)

**Comment by lordofhyphens** [comment]
Yeah, I am not a user of RepetierHost and I will likely never be one.

If Gcode.ws and Slic3r both generally agree that there is no major issue, I am comfortable closing this.

I suspect that Printrun would also show all is well.

If the gcode output from Slic3r is missing those areas then I will reopen.

**Comment by TaiTair** [comment]
I was just about to close it but you beat me to it. The print was flawless and the problem comes from RepetierHost's preview system. 

Thanks for taking the time, cheers.
