### ISSUE TITLE
Slic3r under certain conditions when loading external configs

### ISSUE THREAD

**Issue by lordofhyphens** [slic3r/Slic3r#4571]
**Describe the bug**
Slic3r crashes when loading filament_settings_id option under some circumstances, such as provided.

**To Reproduce**

1. Download [config.zip](https://github.com/slic3r/Slic3r/files/2527790/config.zip)
1. Extract config.ini
1. Go to File->Load Config
1. Select config.ini
4. Watch it crash with a segfault.

**3D Model and Slic3r Configuration Export**
[config.zip](https://github.com/slic3r/Slic3r/files/2527790/config.zip)

**Expected behavior**
Slic3r does not crash on loading config.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 1.3.1-dev d9c1d459c5744aa880cd0c5e9093b0ee42f5321b

**Additional context**
Workaround is to manually edit the configuration to avoid the bug state. filament_settings_id is not being loaded from defaults appropriately when going from a single extruder to multiple extruder. 

Add `filament_settings_id = ` with N-1 semicolons, where N is the number of extruders.

Abbreviated traceback from coredump:
````
#0  0x00007f2600775b06 in Slic3r::ConfigBase__set(Slic3r::ConfigBase*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, sv*) (THIS=<optimized out>, opt_key=..., value=<optimized out>)
    at /usr/include/c++/8/ext/new_allocator.h:79
#1  0x00007f26006ad428 in XS_Slic3r__Config_set(interpreter*, cv*) (my_perl=<optimized out>, cv=<optimized out>) at /usr/bin/perl -MExtUtils::XSpp::Cmd -e xspp -- -t "../xsp/typemap.xspt"  "../xsp/Config.xsp":83
#2  0x000055985c6c9741 in Perl_pp_entersub ()
#3  0x000055985c6c1676 in Perl_runops_standard ()

````

**Comment by gege2b** [comment]
No crash at all on my linux mint, not even a warning or something similar, settings seems to be properly loaded

**Comment by lordofhyphens** [comment]
#4577 reverts the change to the config system.

**Comment by lordofhyphens** [comment]
Going to close as I reverted the related change.
