### ISSUE TITLE
Question regarding files

### ISSUE THREAD

**Issue by JamesVerner** [slic3r/Slic3r#4572]
Hey, it isn't asking about code or anything. I'm just trying to work out what some of these classes do. Would anyone know roughly what:

#include "../BoundingBox.hpp"
#include "../ExPolygon.hpp"
#include "../Polyline.hpp"
#include "../PrintConfig.hpp" - Defines the values for the patterns which are used in the GUI. 

I'm just curiously what they exactly do in order to produce a pattern, thanks.

**Comment by lordofhyphens** [comment]
The first is a description of the bounding box (the square containing the shape).

The other two are data structures to represent the pattern and area to be filled. 

https://manual.slic3r.org/libslic3r-doc/

**Comment by JamesVerner** [comment]
Thank you!
