### ISSUE TITLE
Settings dialogs are opened multiple times

### ISSUE THREAD

**Issue by alranel** [slic3r/Slic3r#4588]
When the "Display profile editors as tabs" is unchecked, each press of the cogs will launch a new dialog. So multiple dialogs will open for the same category.

Is this a feature or a bug? :-)

**Comment by alranel** [comment]
It's an outgrowth of how the dialog isn't modal. I think opening multiple dialogs is confusing (and not sure we handle the concurrency well). I propose to keep the dialogs non-modal, and just re-activating the existing dialog whenever the cog is pressed again.

**Comment by lordofhyphens** [comment]
I can agree with that.

**Comment by hellraiserinchief** [comment]
As my first contribution to an OSS, I would like to submit a PR for this issue. ( Aiming to get an Hacktoberfest t-shirt )

I added a hash variable to Slic3r::GUI::Plater to save references the first settings dialogs that were opened, and a function to show those saved dialogs. 

I am at best a novice in wxwidgets, I could not find a way to re-focus the dialogs, when the cogs are clicked. Any hints in this direction are welcome.

**Comment by hellraiserinchief** [comment]
Hi, can someone please review the pull request. Thank you.
