### ISSUE TITLE
Question - Generating the actual shape of the pillar 

### ISSUE THREAD

**Issue by JamesVerner** [slic3r/Slic3r#4601]
Hey, sorry to ask anyone on the issue tracker. However, I'm trying to figure out where in the supportmaterial.pm the actual shape of the pillars are being generated. Would anyone know where it could be found? I found the location for infills in supportmaterial.pm but not the actual pillar.

**Comment by alranel** [comment]
There's a function called `generate_pillars_shape`:

https://github.com/slic3r/Slic3r/blob/44d145d986c7bf5124910de1b561836071bf8305/lib/Slic3r/Print/SupportMaterial.pm#L904
