### ISSUE TITLE
Dropping support for old distros for Slic3r AppImage

### ISSUE THREAD

**Issue by lordofhyphens** [slic3r/Slic3r#4630]
I am considering dropping all support for all old distros (those that don't ship with a libstdc++ new enough to use C++11/14) for the AppImage.

Adding libstdc++ to the AppImage is breaking new distros.

**Comment by lordofhyphens** [comment]
I think I have a workaround, borrowed from the notes and script implementation at https://docs.appimage.org/packaging-guide/other-resources/ingredients.html

**Comment by lordofhyphens** [comment]
Thanks to @darealshinji for the AppImage-checkrt repository, from where I shamelessly stole the pieces.

**Comment by darealshinji** [comment]
You're welcome.
