### ISSUE TITLE
Speed issue with Slic3r

### ISSUE THREAD

**Issue by athulsnair** [slic3r/Slic3r#4638]
**Describe the bug:** Actual print speed is different than the one given. Print speeds are set at 50 mm/sec. But first layer is printed at a higher spped than other layers. In remaining layers, inner two layers are printed slower outer perimeter faster

**To Reproduce:**  slice with following configurations
gcode can be found in attached file. Print video can also found in zip file
[Slic3r.zip](https://github.com/slic3r/Slic3r/files/2649644/Slic3r.zip)

**3D Model and Slic3r Configuration Export:**  

3D model and used Slic3r configurations can be found in attachment

**Expected behavior:** Same print speed for all layers

**Desktop (please complete the following information):**
Slic3r version is: 1.3.1 dev
Windows 8

**Other information:** Printer is for printing Clay not Plastic

**Comment by athulsnair** [comment]
I thought it might be a firmware problem too. It's not.

The problem is with the "Filament Settings" of Slic3r

[new_config-20181206T070832Z-001.zip](https://github.com/slic3r/Slic3r/files/2652033/new_config-20181206T070832Z-001.zip)

This is a new configuration. Use "Filament settings" from this config. It is same as initially uploaded configurations "Filament Settings", but this one prints at proper speed

**Comment by foreachthing** [comment]
@athulsnair I noticed that, too!
But now ... what was the problem exactly?

**Comment by VanessaE** [comment]
Please attach an example model also.

You have auto-cooling enabled with a minimum layer time of 30 seconds. If a layer should take less than that, Slic3r will slow down internal perimters, infill, etc. to kill time, leaving exterior perimeters at their configured speed.  Your video suggests exactly that.

**Comment by athulsnair** [comment]
@VanessaE Model can be found inside the zip file that I attached to first comment. May be it has to do with the cooling. I will check that.

@foreachthing I though it might be a bug. At higher nozzle size and layer height, it fails to follow the print speed given.
I make "cooling" settings same for both and reply

**Comment by VanessaE** [comment]
Oh right, not sure how I missed that model.  Loaded and sliced with one of my configs, and as expected, small layer times.  With two perimeters, zero infill, no auto-cooling/slow-down, and a flat 30 mm/s, I get layer times in the 8 second range.
