### ISSUE TITLE
Slicer crashes upon clicking 'split'

### ISSUE THREAD

**Issue by sixuannn** [slic3r/Slic3r#4649]
**Describe the bug**
It literally just crashes (aka closes itself) when I try to split something.

**To Reproduce**
1. Click on model
2. Right click 
3. Press split
4. Crashes

**3D Model and Slic3r Configuration Export**
Please upload a ZIP archive containing a copy of the 3D model you are seeing this bug with and a CTRL-E export of the configuration used.

**Expected behavior**
I expected it to be able to split a model

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 1.41.1+
     - _Do not report Prusa3D Slic3r bugs here without confirming it is a problem on a development release of Slic3r, or your issue will be closed. *Only* use normal Slic3r version IDs._
     - _For -dev versions, use `git describe --tag` or get the hash value for the version you downloaded or `git rev-parse HEAD`_
     - _Use `About->About Slic3r` for release versions._

**Additional context**

**Comment by VanessaE** [comment]
Um, Slic3r is only up to 1.3.x, are you sure you meant to post here and not on the Slic3r PE issue tracker?

Anyway it works fine for me at commit 21eb603c with one of my models -- can't reproduce.  Please attach a model that fails for you.

**Comment by sixuannn** [comment]
Hi, 
My apologies! I think I posted on the wrong place. Still new at this, so sorry!

**Comment by VanessaE** [comment]
No worries.  Happens all the time.

**Comment by supermerill** [comment]
@sixuannn : see https://github.com/prusa3d/Slic3r/issues/1464
