### ISSUE TITLE
Plater window always visible

### ISSUE THREAD

**Issue by wnc2** [slic3r/Slic3r#4656]
**Is your feature request related to a problem? Please describe.**

feature request
![schermata 2018-12-29 alle 16 29 06](https://user-images.githubusercontent.com/43959480/50539807-e2cb2c80-0b86-11e9-8372-d4b5ed9cc971.jpg)

**Describe the solution you'd like**

i wish to always see the plater window, during working on each of the other 3 Print/Fliament/Printer windows, so with background processing ON, i could see changes in realtime, very useful for beginners.

Print/Fliament/Printer windows could be opened on the left side of plater window

**Describe alternatives you've considered**

**Additional context**
![schermata 2018-12-29 alle 16 29 06](https://user-images.githubusercontent.com/43959480/50539957-3a6a9780-0b89-11e9-9e5f-ff4ab0630335.jpg)

**Comment by lordofhyphens** [comment]
Slic3r already lets you set up the profile editors as dialogs instead of tabs (File->Preferences).
