### ISSUE TITLE
persistent M600 after deleting a STL

### ISSUE THREAD

**Issue by wnc2** [slic3r/Slic3r#4658]
**Describe the bug**
Added M600 remain also after deleting related stl from plater

**To Reproduce**

- i load a stl
- i set some M600 points and background process slices automatically
- i delete stl
- i load another stl 
- M600 points still present
- if i dont check, i create a gcode with M600 of the previous print

issue obvioulsy doesnt happen if second stl is lower than previous M600 points

**3D Model and Slic3r Configuration Export**
Please upload a ZIP archive containing a copy of the 3D model you are seeing this bug with and a CTRL-E export of the configuration used.

**Expected behavior**
M600 points disappear if i empty the plater

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Windows]
MacOS
 - Version [e.g. 1.3.0]
     1.42.0 alpha

**Additional context**

**Comment by lordofhyphens** [comment]
AFAIK Slic3r doesn't emit M600 at all.
