### ISSUE TITLE
v1.3.1-dev-45353b7: Division by zero if max_layer_height == min_layer_height

### ISSUE THREAD

**Issue by 7eggert** [slic3r/Slic3r#4670]
### Version
Slic3r-1.3.1-dev-45353b7-x86_64.AppImage

### Operating system type + version
Linux be10 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux

### Behavior
Set extruder limits to 0.1 mm / 0.1 mm
Load any STL
Right click → settings

Resulting crash:
**Illegal division by zero at /home/7eggert/.lib/slic3r-1.3.1-dev-d17659b-linux-x64/local-lib/lib/perl5/Slic3r/GUI/Plater/SplineControl.pm line 270.**

I don't believe the config to be necessary, but here it is:
[config.ini.gz](https://github.com/slic3r/Slic3r/files/2721345/config.ini.gz)

PS and OT: On Printer Settings → Extruder $n → Limits, the label should say "Layer Height Limits" instead of "Limits"

**Comment by lordofhyphens** [comment]
@7eggert new AppImage should be coming down soonish (look for PR4672 in the name in https://dl.slic3r.org/dev/linux/branches).
