### ISSUE TITLE
View shouldn't be reset to 3D view after each changes

### ISSUE THREAD

**Issue by XReyRobert** [slic3r/Slic3r#4676]
I really like to see effect of changes on the internal structure of layers (Preview view).
When preview is selected to a certain layer, any print configuration change will result in the view defaulting to  "3D" first tab. It would be very nice and efficient if it could stay on the selected preview/layer

**Comment by lordofhyphens** [comment]
Turn on background processing.

**Comment by XReyRobert** [comment]
many thanks
