### ISSUE TITLE
Slic3r prints supports with only raft turned on

### ISSUE THREAD

**Issue by johnjensen2** [slic3r/Slic3r#4698]
Same as title.

Attached files per LOH 

[config.txt](https://github.com/slic3r/Slic3r/files/2752859/config.txt)

[ella_oc_a015R.stl.txt](https://github.com/slic3r/Slic3r/files/2752861/ella_oc_a015R.stl.txt)

**Comment by lordofhyphens** [comment]
So which version of Slic3r is this? Can you reproduce with a build from https://dl.slic3r.org/dev ?

**Comment by lordofhyphens** [comment]
![image](https://user-images.githubusercontent.com/31754/51082409-ebb21700-16cb-11e9-939a-736dfd572d7a.png)

**Comment by johnjensen2** [comment]
1.29 and i will check it

**Comment by lordofhyphens** [comment]
You'll have to post a layer screenshot of it breaking (similar to my 3d preview here).

**Comment by lordofhyphens** [comment]
Use 1.3.0 at least, if not 1.3.1-dev. We provide AppImages.
