### ISSUE TITLE
Notification when exported

### ISSUE THREAD

**Issue by kajsilander78** [slic3r/Slic3r#4704]
Hi!
Would someone be kind to add a option to specify a
command line to be run when export has finished?
Would be practical to get notification when gcode export has finished.
A command line could enable the user to choose way to be notified (message, sound, etc.)

**Comment by supermerill** [comment]
https://manual.slic3r.org/advanced/post-processing ?

**Comment by kajsilander78** [comment]
Oh, sorry missed that...closing
