### ISSUE TITLE
Slic3r : terminate called after throwing an instance of 'Slic3r::UnknownOptionException"

### ISSUE THREAD

**Issue by julys54110** [slic3r/Slic3r#4719]
### Do not report Prusa3D Slic3r bugs here without confirming it is a problem on a development release of Slic3r, or your issue will be closed. [Development builds of Slic3r](https://dl.slic3r.org/dev). [Prusa3D Issue Tracker](https://github.com/Prusa3D/Slic3r/issues)

**Describe the bug**

I've built Slic3r C++ source code with cmake on Debian 9.

When i launch, i have this message :

>     terminate called after throwing an instance of 'Slic3r::UnknownOptionException.

How to fix the options correctly?

**To Reproduce**
I launch Slic3r

**3D Model and Slic3r Configuration Export**
No model or configuration

**Expected behavior**
No exception

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 9
 - Version : 1.3.0-1292-g66b00c90

**Additional context**

**Comment by lordofhyphens** [comment]
I believe what is going on here is that the CLI frontend needs a bit of rework to handle these exceptions.

**Comment by julys54110** [comment]
ok thank you

**Comment by lordofhyphens** [comment]
It is still a bug :p

**Comment by madscientist159** [comment]
I'm still seeing this.  Any fix yet?

**Comment by lordofhyphens** [comment]
The CLI front end is pickier about options in configurations. Current workaround is to remove the offending option from your input config.

**Comment by lordofhyphens** [comment]
@madscientist159 you should post a copy of the config you are trying to use.

**Comment by lordofhyphens** [comment]
I see what happened. @alranel made the config options throw exceptions now, and there are quite a few "special" options that aren't necessarily set. I'm looking into where it gets used so I can sort it out.

**Comment by lordofhyphens** [comment]
Thanks to @zdroyer this should be sorted out
