### ISSUE TITLE
Slic3r.appimage desktop icon is barely visible

### ISSUE THREAD

**Issue by LongLiveCHIEF** [slic3r/Slic3r#4721]
**Describe the bug**
When using `appimagetool` or `AppImageLauncher`  to create desktop integrations, the desktop icon used is 

![current desktop icon](https://raw.githubusercontent.com/slic3r/Slic3r/master/var/Slic3r_192px_transparent.png)

This results in a image that is almost completely transparent in the launcher and on the desktop bar.  This PR instead uses a less transparent image already in this repository:

![proposed desktop icon](https://raw.githubusercontent.com/slic3r/Slic3r/master/var/Slic3r_192px.png)

**To Reproduce**
1. Install Use [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) or `appimagetool` to install/extract desktop integrations for Linux
1. Results in almost completely transparent icon on desktoop/toolbars/finders (on Linux)

**Expected behavior**
Icon should be easily visible on desktop integration points on Ubuntu/Linux.

**Screenshots**

These were taken side-by-side. Each are from the extracted squashfs from the AppImage. The one on the left is the one the desktop file winds up pointing to, whereas the one on the right is the one this PR will cause it to point to.
![screenshot from 2019-02-01 14-37-53](https://user-images.githubusercontent.com/3282305/52153140-7daf9e80-263e-11e9-8406-8cb4aced1359.png)

**Desktop (please complete the following information):**
 - OS: `Ubuntu 18.04 Gnome`
 - Version `Slic3r-1.3.0-x86_64.AppImage`

**Additional context**

There wasn't any documentation about how to build the appimage locally, and it appears some of the travis stuff might be hardcoded in for directory/locations. I spent a few hours getting familiar with the `appimage` ecosystem and tooling (fun stuff!) but still couldn't get the `package/linux/appimage.sh` to run locally to verify expected outcome on Linux. Basically I can't tell what directory and with what params to run the `package/linux/appimage.sh` from/with. 

It looks like an `.appimage` will be built with a PR, so hoping to test with that.

**Comment by lordofhyphens** [comment]
They get built, but only uploaded when the originating branch is on the slic3r/Slic3r
