### ISSUE TITLE
"simplication" of contour polygons: remove collinear points from tesselation artifacts

### ISSUE THREAD

**Issue by platsch** [slic3r/Slic3r#4726]
Consider a simple object like this:

![object](https://user-images.githubusercontent.com/4190756/52268703-7dfcb200-293c-11e9-9277-c1cce2dd7ec6.png)

The cylinder is composed of a number of rectangular surfaces, which is a very common pattern for many objects. The tesselated representation of this model looks like this:

![object_tesselated_label](https://user-images.githubusercontent.com/4190756/52283613-14dc6500-2963-11e9-8b8a-be2c9e017094.png)

All rectangular surfaces are now split into triangles. When slicing this model, the result looks like this (Layer 5):

![layer_5](https://user-images.githubusercontent.com/4190756/52282706-523ff300-2961-11e9-9c7a-462945e47112.png)

Every additional triangle line (red marker in the tesselated image) in each rectangle causes slic3r to add a point which is perfectly collinear with its two neighbors, but entirely useless.
Most (but not all!) of the redundant points are removed during the gcode-export by the Douglas-Peucker algorithm (invoked via polygon.simplify [here](https://github.com/slic3r/Slic3r/blob/master/xs/src/libslic3r/GCode.cpp#L323), but all polygon operations during the entire slicing process have to respect the useless points.

Is there any specific reason to keep collinear polygon points? If not, I propose to remove them right after or during the `slice()` step in TriangleMeshSlicer.
I did an implementation of this, the result for the same object is as expected:

![layer_5_no_collinear](https://user-images.githubusercontent.com/4190756/52283368-9ed7fe00-2962-11e9-9598-4e728c9adb5a.png)

Some quick tests with different objects indicated a speedup of the full slicing process between 10% and 30%, but I did not extensively test this.  Worst case would be a model purely composed of triangles which do not assemble a larger, planar surface. In this case the `remove_collinear_points` would add some overhead.

I also noted a `remove_vertical_collinear_points` method in Polygon.cpp which is apparently used for rectilinear infill patterns, but I'm not sure whether a general implementation of remove_collinear_points could replace this.

If there is no obvious reason to not apply this simplification, I can quickly file a PR with my implementation.

**Comment by lordofhyphens** [comment]
Probably fine, although there was related work for curve fitting.

**Comment by platsch** [comment]
Can you point me somewhere? I'm not familiar with the curve fitting stuff

**Comment by lordofhyphens** [comment]
https://github.com/slic3r/Slic3r/issues/23

**Comment by platsch** [comment]
OK, sorry, I was actually aware of this thread. But I don't see how exactly it is related to this issue. I didn't look at the code in #23, is it because arc detection also has the problem of collinear points, preventing a correct detection? Or is there a solution for the problem I described in the arc-detection approach?
