### ISSUE TITLE
Master branch isn't compiled.

### ISSUE THREAD

**Issue by Splarv** [slic3r/Slic3r#4727]
macOs  Mojave 10.14.2
Soft installed by instructions (homebrew variant):
https://github.com/slic3r/Slic3r/wiki/Running-Slic3r-from-git-on-OS-X
$ git status -v
On branch master
Your branch is up to date with 'origin/master'.
$ git remote -v
origin	https://github.com/slic3r/Slic3r.git (fetch)
origin	https://github.com/slic3r/Slic3r.git (push)
$ git branch -v
* master 66b00c9 Fix typo.

````
$ perl Build.PL --gui
/usr/local/bin/cpanm
App::cpanminus is up to date. (1.7044)
Class::Accessor is up to date. (0.51)
Growl::GNTP is up to date. (0.21)
LWP::UserAgent is up to date. (6.36)
Net::Bonjour is up to date. (0.96)
OpenGL is up to date. (0.70)
Socket is up to date. (2.027)
--> Working on Wx
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Wx-0.9932.tar.gz ... OK
==> Found dependencies: Alien::wxWidgets
--> Working on Alien::wxWidgets
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Alien-wxWidgets-0.69.tar.gz ... OK
Configuring Alien-wxWidgets-0.69 ... OK
Building and testing Alien-wxWidgets-0.69 ... 	FAIL
! Installing Alien::wxWidgets failed. See /Users/olleg/.cpanm/work/1549471755.64048/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Alien::wxWidgets' is not installed
! Bailing out the installation for Wx-0.9932.
--> Working on Wx::GLCanvas
Fetching http://www.cpan.org/authors/id/M/MB/MBARBON/Wx-GLCanvas-0.09.tar.gz ... OK
==> Found dependencies: Wx::build::MakeMaker
--> Working on Wx::build::MakeMaker
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Wx-0.9932.tar.gz ... OK
==> Found dependencies: Alien::wxWidgets
--> Working on Alien::wxWidgets
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Alien-wxWidgets-0.69.tar.gz ... OK
Configuring Alien-wxWidgets-0.69 ... OK
Building and testing Alien-wxWidgets-0.69 ... FAIL
! Installing Alien::wxWidgets failed. See /Users/olleg/.cpanm/work/1549471771.64572/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Alien::wxWidgets' is not installed
! Bailing out the installation for Wx-0.9932.
! Installing the dependencies failed: Module 'Wx::build::MakeMaker' is not installed
! Bailing out the installation for Wx-GLCanvas-0.09.
Don't worry, this module is optional.
The following prerequisites failed to install: Wx
````

**Comment by Splarv** [comment]
.cpanm/work/1549471771.64572/build.log

cpanm (App::cpanminus) 1.7044 on perl 5.028001 built for darwin-thread-multi-2level
Work directory is /Users/olleg/.cpanm/work/1549471771.64572
You have make /usr/bin/make
You have LWP 6.36
You have /usr/bin/tar: bsdtar 2.8.3 - libarchive 2.8.3
You have /usr/bin/unzip
Searching Wx::GLCanvas (0) on cpanmetadb ...
--> Working on Wx::GLCanvas
Fetching http://www.cpan.org/authors/id/M/MB/MBARBON/Wx-GLCanvas-0.09.tar.gz
-> OK
Unpacking Wx-GLCanvas-0.09.tar.gz
Entering Wx-GLCanvas-0.09
Checking configure dependencies from META.yml
Checking if you have Wx::build::MakeMaker 0.16 ... No
==> Found dependencies: Wx::build::MakeMaker
Searching Wx::build::MakeMaker (0.16) on cpanmetadb ...
--> Working on Wx::build::MakeMaker
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Wx-0.9932.tar.gz
-> OK
Unpacking Wx-0.9932.tar.gz
Entering Wx-0.9932
Checking configure dependencies from META.json
Checking if you have Alien::wxWidgets 0.25 ... No
==> Found dependencies: Alien::wxWidgets
Searching Alien::wxWidgets (0.25) on cpanmetadb ...
--> Working on Alien::wxWidgets
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Alien-wxWidgets-0.69.tar.gz
-> OK
Unpacking Alien-wxWidgets-0.69.tar.gz
Entering Alien-wxWidgets-0.69
Checking configure dependencies from META.json
Checking if you have ExtUtils::Install 1.46 ... Yes (2.14)
Checking if you have Module::Build 0.38 ... Yes (0.4224)
Configuring Alien-wxWidgets-0.69
Running Build.PL
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Alien-wxWidgets' version '0.69'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have LWP::Protocol::https 0 ... Yes (6.07)
Checking if you have ExtUtils::CBuilder 0.24 ... Yes (0.280230)
Checking if you have Module::Pluggable 2.6 ... Yes (5.2)
Checking if you have Module::Build 0.28 ... Yes (0.4224)
Checking if you have File::Spec 1.50 ... Yes (3.75)
Building and testing Alien-wxWidgets-0.69
Argument "0.21_01" isn't numeric in numeric ge (>=) at inc/latest/private.pm line 32.
Building Alien-wxWidgets
Fetching wxWidgets...
fetching from: http://prdownloads.sourceforge.net/wxwindows/wxWidgets-3.0.2.tar.bz2
Extracting wxWidgets...
Patching wxWidgets...
Applying patch: /Users/olleg/.cpanm/work/1549471771.64572/Alien-wxWidgets-0.69/patches/wxWidgets-2.9.0-magic.patch
/usr/local/Cellar/perl/5.28.1/bin/perl ../inc/bin/patch -N -p0 -u -b .bak < ../patches/wxWidgets-2.9.0-magic.patch
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- src/generic/grid.cpp	2009-09-04 06:52:48.000000000 +0200
|+++ src/generic/grid.cpp	2009-10-18 14:43:42.000000000 +0200
--------------------------
Patching file src/generic/grid.cpp using Plan A...
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 12330.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 12331.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 12331.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 12331.
Hunk #1 succeeded at 6125.
    Offset: 528
done
Applying patch: /Users/olleg/.cpanm/work/1549471771.64572/Alien-wxWidgets-0.69/patches/wxWidgets-3.0.2-webkit.patch
/usr/local/Cellar/perl/5.28.1/bin/perl ../inc/bin/patch -N -p0 -u -b .bak < ../patches/wxWidgets-3.0.2-webkit.patch
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff -u include/wx/defs.h include/wx/defs.h
|--- include/wx/defs.h	2014-10-06 22:33:44.000000000 +0100
|+++ include/wx/defs.h	2017-04-08 18:52:20.308109800 +0100
--------------------------
Patching file include/wx/defs.h using Plan A...
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 6353.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 6353.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 6358.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 6358.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 6359.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 6359.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 6361.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 6361.
Hunk #1 succeeded at 3169.
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff -u include/wx/html/webkit.h include/wx/html/webkit.h
|--- include/wx/html/webkit.h	2014-10-06 22:33:44.000000000 +0100
|+++ include/wx/html/webkit.h	2017-04-08 18:53:34.608334300 +0100
--------------------------
Patching file include/wx/html/webkit.h using Plan A...
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 44.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 45.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 45.
Hunk #1 succeeded at 18.
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 222.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 223.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 223.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 223.
Hunk #2 succeeded at 106.
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff -u include/wx/osx/webview_webkit.h include/wx/osx/webview_webkit.h
|--- include/wx/osx/webview_webkit.h	2014-10-06 22:33:44.000000000 +0100
|+++ include/wx/osx/webview_webkit.h	2017-04-08 18:56:04.314415300 +0100
--------------------------
Patching file include/wx/osx/webview_webkit.h using Plan A...
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 324.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 325.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 325.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 325.
Hunk #1 succeeded at 158.
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff -u src/osx/webview_webkit.mm src/osx/webview_webkit.mm
|--- src/osx/webview_webkit.mm	2014-10-06 22:33:44.000000000 +0100
|+++ src/osx/webview_webkit.mm	2017-04-08 19:03:24.676146300 +0100
--------------------------
Patching file src/osx/webview_webkit.mm using Plan A...
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 600.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 601.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 601.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 601.
Hunk #1 succeeded at 296.
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 618.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 619.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 619.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 619.
Hunk #2 succeeded at 305.
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 636.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 637.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 637.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 637.
Hunk #3 succeeded at 314.
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 896.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 897.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 897.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 897.
Hunk #4 succeeded at 442.
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 912.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 913.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 913.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 913.
Hunk #5 succeeded at 450.
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 1750.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 1751.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 1751.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 1751.
Hunk #6 succeeded at 849.
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 1766.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 1767.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 1767.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 1767.
Hunk #7 succeeded at 857.
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 1782.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 1783.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 1783.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 1783.
Hunk #8 succeeded at 865.
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 1798.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 1799.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 1799.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 1799.
Hunk #9 succeeded at 873.
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 2102.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 2103.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 2103.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 2103.
Hunk #10 succeeded at 1007.
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 2540.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 2541.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 2541.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 2541.
Hunk #11 succeeded at 1197.
print() on unopened filehandle NULL at ../inc/bin/patch line 716, <IN> line 2878.
print() on unopened filehandle NULL at ../inc/bin/patch line 717, <IN> line 2879.
print() on unopened filehandle NULL at ../inc/bin/patch line 720, <IN> line 2879.
print() on unopened filehandle NULL at ../inc/bin/patch line 726, <IN> line 2879.
Hunk #12 succeeded at 1335.
done
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
checking build system type... x86_64-apple-darwin18.2.0
checking host system type... x86_64-apple-darwin18.2.0
checking for --disable-gui... no
checking for --enable-monolithic... no
checking for --enable-plugins... no
checking for --without-subdirs... no
checking for --enable-official_build... no
checking for --disable-all-features... no
checking for --enable-universal... no
checking for --enable-nanox... no
checking for --enable-gpe... no
checking for toolkit... osx_cocoa
checking for --with-libpng... yes
checking for --with-libjpeg... yes
checking for --with-libtiff... yes
checking for --without-libjbig... no
checking for --without-liblzma... no
checking for --with-libxpm... yes
checking for --with-libiconv... yes
checking for --with-libmspack... no
checking for --without-gtkprint... no
checking for --with-gnomevfs... no
checking for --with-libnotify... yes
checking for --with-hildon... no
checking for --with-opengl... yes
checking for --with-dmalloc... no
checking for --with-sdl... no
checking for --with-regex... yes
checking for --with-zlib... yes
checking for --with-expat... yes
checking for --with-macosx-sdk... 
checking for --with-macosx-version-min... 10.7
checking for --enable-debug... default
checking for --disable-debug_flag... no
checking for --enable-debug_info... no
checking for --enable-debug_gdb... no
checking for --enable-debug_cntxt... no
checking for --enable-mem_tracing... no
checking for --disable-shared... no
checking for --enable-stl... no
checking for --enable-std_containers... no
checking for --enable-std_iostreams... yes
checking for --enable-std_string... yes
checking for --enable-std_string_conv_in_wxstring... no
checking for --disable-unicode... no
checking for --enable-mslu... no
checking for --enable-utf8... no
checking for --enable-utf8only... no
checking for --enable-extended_rtti... no
checking for --disable-optimise... no
checking for --enable-profile... no
checking for --enable-no_rtti... no
checking for --enable-no_exceptions... no
checking for --enable-permissive... no
checking for --enable-no_deps... no
checking for --disable-vararg_macros... no
checking for --enable-universal_binary... no
checking for --enable-macosx_arch... no
checking for --enable-compat26... no
checking for --disable-compat28... no
checking for --disable-rpath... no
checking for --enable-objc_uniquifying... no
checking for --disable-visibility... no
checking for --disable-tls... no
checking for --enable-intl... yes
checking for --enable-xlocale... yes
checking for --enable-config... yes
checking for --enable-protocols... yes
checking for --enable-ftp... yes
checking for --enable-http... yes
checking for --enable-fileproto... yes
checking for --enable-sockets... yes
checking for --enable-ipv6... no
checking for --enable-ole... yes
checking for --enable-dataobj... yes
checking for --enable-ipc... yes
checking for --enable-baseevtloop... yes
checking for --enable-epollloop... yes
checking for --enable-selectloop... yes
checking for --enable-any... yes
checking for --enable-apple_ieee... yes
checking for --enable-arcstream... yes
checking for --enable-base64... yes
checking for --enable-backtrace... yes
checking for --enable-catch_segvs... yes
checking for --enable-cmdline... yes
checking for --enable-datetime... yes
checking for --enable-debugreport... yes
checking for --enable-dialupman... yes
checking for --enable-dynlib... yes
checking for --enable-dynamicloader... yes
checking for --enable-exceptions... yes
checking for --enable-ffile... yes
checking for --enable-file... yes
checking for --enable-filehistory... yes
checking for --enable-filesystem... yes
checking for --enable-fontenum... yes
checking for --enable-fontmap... yes
checking for --enable-fs_archive... yes
checking for --enable-fs_inet... yes
checking for --enable-fs_zip... yes
checking for --enable-fsvolume... yes
checking for --enable-fswatcher... yes
checking for --enable-geometry... yes
checking for --enable-log... yes
checking for --enable-longlong... yes
checking for --enable-mimetype... yes
checking for --enable-printfposparam... yes
checking for --enable-snglinst... yes
checking for --enable-sound... yes
checking for --enable-stdpaths... yes
checking for --enable-stopwatch... yes
checking for --enable-streams... yes
checking for --enable-sysoptions... yes
checking for --enable-tarstream... yes
checking for --enable-textbuf... yes
checking for --enable-textfile... yes
checking for --enable-timer... yes
checking for --enable-variant... yes
checking for --enable-zipstream... yes
checking for --enable-url... yes
checking for --enable-protocol... yes
checking for --enable-protocol_http... yes
checking for --enable-protocol_ftp... yes
checking for --enable-protocol_file... yes
checking for --enable-threads... yes
checking for --enable-iniconf... no
checking for --enable-regkey... yes
checking for --enable-docview... yes
checking for --enable-help... yes
checking for --enable-mshtmlhelp... yes
checking for --enable-html... yes
checking for --enable-htmlhelp... yes
checking for --enable-xrc... yes
checking for --enable-aui... yes
checking for --enable-propgrid... yes
checking for --enable-ribbon... yes
checking for --enable-stc... yes
checking for --enable-constraints... yes
checking for --enable-loggui... yes
checking for --enable-logwin... yes
checking for --enable-logdialog... yes
checking for --enable-mdi... yes
checking for --enable-mdidoc... yes
checking for --enable-mediactrl... auto
checking for --enable-gstreamer8... no
checking for --enable-richtext... yes
checking for --enable-postscript... yes
checking for --enable-printarch... yes
checking for --enable-svg... yes
checking for --enable-webkit... yes
checking for --enable-webview... yes
checking for --enable-clipboard... yes
checking for --enable-dnd... yes
checking for --disable-controls... no
checking for --enable-markup... yes
checking for --enable-accel... yes
checking for --enable-animatectrl... yes
checking for --enable-bannerwindow... yes
checking for --enable-artstd... yes
checking for --enable-arttango... auto
checking for --enable-bmpbutton... yes
checking for --enable-bmpcombobox... yes
checking for --enable-button... yes
checking for --enable-calendar... yes
checking for --enable-caret... yes
checking for --enable-checkbox... yes
checking for --enable-checklst... yes
checking for --enable-choice... yes
checking for --enable-choicebook... yes
checking for --enable-collpane... yes
checking for --enable-colourpicker... yes
checking for --enable-combobox... yes
checking for --enable-comboctrl... yes
checking for --enable-commandlinkbutton... yes
checking for --enable-dataviewctrl... yes
checking for --enable-datepick... yes
checking for --enable-detect_sm... yes
checking for --enable-dirpicker... yes
checking for --enable-display... yes
checking for --enable-editablebox... yes
checking for --enable-filectrl... yes
checking for --enable-filepicker... yes
checking for --enable-fontpicker... yes
checking for --enable-gauge... yes
checking for --enable-grid... yes
checking for --enable-headerctrl... yes
checking for --enable-hyperlink... yes
checking for --enable-imaglist... yes
checking for --enable-infobar... yes
checking for --enable-listbook... yes
checking for --enable-listbox... yes
checking for --enable-listctrl... yes
checking for --enable-notebook... yes
checking for --enable-notifmsg... yes
checking for --enable-odcombobox... yes
checking for --enable-popupwin... yes
checking for --enable-prefseditor... yes
checking for --enable-radiobox... yes
checking for --enable-radiobtn... yes
checking for --enable-richmsgdlg... yes
checking for --enable-richtooltip... yes
checking for --enable-rearrangectrl... yes
checking for --enable-sash... yes
checking for --enable-scrollbar... yes
checking for --enable-searchctrl... yes
checking for --enable-slider... yes
checking for --enable-spinbtn... yes
checking for --enable-spinctrl... yes
checking for --enable-splitter... yes
checking for --enable-statbmp... yes
checking for --enable-statbox... yes
checking for --enable-statline... yes
checking for --enable-stattext... yes
checking for --enable-statusbar... yes
checking for --enable-taskbaricon... yes
checking for --enable-tbarnative... yes
checking for --enable-textctrl... yes
checking for --enable-datepick... yes
checking for --enable-tipwindow... yes
checking for --enable-togglebtn... yes
checking for --enable-toolbar... yes
checking for --enable-toolbook... yes
checking for --enable-treebook... yes
checking for --enable-treectrl... yes
checking for --enable-treelist... yes
checking for --enable-commondlg... yes
checking for --enable-aboutdlg... yes
checking for --enable-choicedlg... yes
checking for --enable-coldlg... yes
checking for --enable-filedlg... yes
checking for --enable-finddlg... yes
checking for --enable-fontdlg... yes
checking for --enable-dirdlg... yes
checking for --enable-msgdlg... yes
checking for --enable-numberdlg... yes
checking for --enable-splash... yes
checking for --enable-textdlg... yes
checking for --enable-tipdlg... yes
checking for --enable-progressdlg... yes
checking for --enable-wizarddlg... yes
checking for --enable-menus... yes
checking for --enable-miniframe... yes
checking for --enable-tooltips... yes
checking for --enable-splines... yes
checking for --enable-mousewheel... yes
checking for --enable-validators... yes
checking for --enable-busyinfo... yes
checking for --enable-hotkey... auto
checking for --enable-joystick... yes
checking for --enable-metafile... auto
checking for --enable-dragimage... yes
checking for --enable-accessibility... no
checking for --enable-uiactionsim... yes
checking for --enable-dctransform... yes
checking for --enable-webviewwebkit... yes
checking for --enable-palette... yes
checking for --enable-image... yes
checking for --enable-gif... yes
checking for --enable-pcx... yes
checking for --enable-tga... yes
checking for --enable-iff... yes
checking for --enable-pnm... yes
checking for --enable-xpm... yes
checking for --enable-ico_cur... yes
checking for --enable-dccache... yes
checking for --enable-ps-in-msw... yes
checking for --enable-ownerdrawn... yes
checking for --enable-uxtheme... yes
checking for --enable-wxdib... yes
checking for --enable-webviewie... yes
checking for --enable-autoidman... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether we are using the Intel C compiler... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc needs -traditional... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether we are using the Intel C++ compiler... no
checking whether we are using the Metrowerks C++ compiler... no
checking whether we are using the IBM xlC C++ compiler... no
checking for ar... ar
checking if C compiler (gcc -mmacosx-version-min=10.7) works with SDK/version options... yes
checking if C++ compiler (g++ -mmacosx-version-min=10.7) works with SDK/version options... configure: error: in `/Users/olleg/.cpanm/work/1549471771.64572/Alien-wxWidgets-0.69/wxWidgets-3.0.2/bld':
configure: error: no.  Try a different SDK
See `config.log' for more details
system: echo exit | sh ../configure --prefix=/Users/olleg/prog/Slic3r/local-lib/lib/perl5/darwin-thread-multi-2level/Alien/wxWidgets/osx_cocoa_3_0_2_uni --with-osx_cocoa --with-opengl --disable-compat24 --enable-unicode  --disable-monolithic --disable-universal_binary  --with-macosx-version-min=10.7 --enable-graphics_ctx: 256 at ./Build line 67.
-> FAIL Installing Alien::wxWidgets failed. See /Users/olleg/.cpanm/work/1549471771.64572/build.log for details. Retry with --force to force install it.
-> FAIL Installing the dependencies failed: Module 'Alien::wxWidgets' is not installed
-> FAIL Bailing out the installation for Wx-0.9932.
-> FAIL Installing the dependencies failed: Module 'Wx::build::MakeMaker' is not installed
-> FAIL Bailing out the installation for Wx-GLCanvas-0.09.

**Comment by lordofhyphens** [comment]
You probably want to install Wx and OpenGL from Homebrew.

On the other hand, the plater doesn't display correctly on Mojave.

**Comment by lordofhyphens** [comment]
Additionally, you can rename logs to .txt and upload to GitHub (and I prefer it that way)

**Comment by Splarv** [comment]
> You probably want to install Wx and OpenGL from Homebrew.

You probably want to improve the instruction for compilation. :)

> On the other hand, the plater doesn't display correctly on Mojave.

Yep, I saw this. If you know too, I don't need to post a bug report about this.

> Additionally, you can rename logs to .txt

done

> upload to GitHub

How? I don't see option in the interface to attach a text file.

**Comment by lordofhyphens** [comment]
I didn't have a Mojave system until #4699 came in and I am still working out building on it.

Your specific compile issue looks like it is down in Alien::wxWidgets (which is not our code). 

I don't recall that failing for me anyway.

Wiki has been updated.

**Comment by Splarv** [comment]
> Wiki has been updated.
Yep, one step close. After installing wxwidgets.

$ perl Build.PL --gui
/usr/local/bin/cpanm
App::cpanminus is up to date. (1.7044)
Class::Accessor is up to date. (0.51)
Growl::GNTP is up to date. (0.21)
LWP::UserAgent is up to date. (6.36)
Net::Bonjour is up to date. (0.96)
OpenGL is up to date. (0.70)
Socket is up to date. (2.027)
--> Working on Wx
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Wx-0.9932.tar.gz ... OK
==> Found dependencies: Alien::wxWidgets
--> Working on Alien::wxWidgets
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Alien-wxWidgets-0.69.tar.gz ... OK
Configuring Alien-wxWidgets-0.69 ... OK
Building and testing Alien-wxWidgets-0.69 ... OK
Successfully installed Alien-wxWidgets-0.69
Configuring Wx-0.9932 ... OK
Building and testing Wx-0.9932 ... FAIL
! Installing Wx failed. See /Users/olleg/.cpanm/work/1549639947.74451/build.log for details. Retry with --force to force install it.
1 distribution installed
--> Working on Wx::GLCanvas
Fetching http://www.cpan.org/authors/id/M/MB/MBARBON/Wx-GLCanvas-0.09.tar.gz ... OK
==> Found dependencies: Wx::build::MakeMaker
--> Working on Wx::build::MakeMaker
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Wx-0.9932.tar.gz ... OK
Configuring Wx-0.9932 ... OK
Building and testing Wx-0.9932 ... FAIL
! Installing Wx::build::MakeMaker failed. See /Users/olleg/.cpanm/work/1549639956.75505/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Wx::build::MakeMaker' is not installed
! Bailing out the installation for Wx-GLCanvas-0.09.
Don't worry, this module is optional.
The following prerequisites failed to install: Wx
