### ISSUE TITLE
[1.42a5] Auto Arrange does not consider Complete Individual Objects

### ISSUE THREAD

**Issue by timur-tabi** [slic3r/Slic3r#4729]
1.42 alpha5, Mac OS X 10.11

When "Complete Individual Objects" is enabled, the Auto Arrange button will group the objects close together as if "Complete Individual Objects" were not enabled.  A dialog box then immediately appears telling me that the objects are too close together.

This does not happen with v1.40.

**Comment by VanessaE** [comment]
Please file Prusa Edition issues on their repo, at https://github.com/prusa3d/Slic3r .  This repo only covers upstream Slic3r.

**Comment by timur-tabi** [comment]
Sorry, I knew something was wrong when I filed this bug.

**Comment by VanessaE** [comment]
Stuff happens :smile:
