### ISSUE TITLE
Master branch isn't compiled after wxwidgets

### ISSUE THREAD

**Issue by Splarv** [slic3r/Slic3r#4731]
macOs Mojave 10.14.2
Soft installed by instructions (homebrew variant):
https://github.com/slic3r/Slic3r/wiki/Running-Slic3r-from-git-on-OS-X
$ git status -v
On branch master
Your branch is up to date with 'origin/master'.
$ git remote -v
origin	https://github.com/slic3r/Slic3r.git (fetch)
origin	https://github.com/slic3r/Slic3r.git (push)
$ git branch -v

* master [66b00c9](https://github.com/slic3r/Slic3r/commit/66b00c90c3121cf0e67ea7a345b42f27098fefe4) Fix typo.

$ perl Build.PL --gui
/usr/local/bin/cpanm
App::cpanminus is up to date. (1.7044)
Class::Accessor is up to date. (0.51)
Growl::GNTP is up to date. (0.21)
LWP::UserAgent is up to date. (6.36)
Net::Bonjour is up to date. (0.96)
OpenGL is up to date. (0.70)
Socket is up to date. (2.027)
--> Working on Wx
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Wx-0.9932.tar.gz ... OK
==> Found dependencies: Alien::wxWidgets
--> Working on Alien::wxWidgets
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Alien-wxWidgets-0.69.tar.gz ... OK
Configuring Alien-wxWidgets-0.69 ... OK
Building and testing Alien-wxWidgets-0.69 ... OK
Successfully installed Alien-wxWidgets-0.69
Configuring Wx-0.9932 ... OK
Building and testing Wx-0.9932 ... FAIL
! Installing Wx failed. See /Users/olleg/.cpanm/work/1549639947.74451/build.log for details. Retry with --force to force install it.
1 distribution installed
--> Working on Wx::GLCanvas
Fetching http://www.cpan.org/authors/id/M/MB/MBARBON/Wx-GLCanvas-0.09.tar.gz ... OK
==> Found dependencies: Wx::build::MakeMaker
--> Working on Wx::build::MakeMaker
Fetching http://www.cpan.org/authors/id/M/MD/MDOOTSON/Wx-0.9932.tar.gz ... OK
Configuring Wx-0.9932 ... OK
Building and testing Wx-0.9932 ... FAIL
! Installing Wx::build::MakeMaker failed. See /Users/olleg/.cpanm/work/1549639956.75505/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Wx::build::MakeMaker' is not installed
! Bailing out the installation for Wx-GLCanvas-0.09.
Don't worry, this module is optional.
The following prerequisites failed to install: Wx

[build.log.txt](https://github.com/slic3r/Slic3r/files/2845716/build.log.txt)

**Comment by lordofhyphens** [comment]
I'm not going to try to troubleshoot building wxmac, it's enough of a headache figuring out what is going on with my system much less anyone else's. Use the homebrew build (which is what the distribution uses).

https://formulae.brew.sh/formula/wxmac

**Comment by Splarv** [comment]
> I'm not going to try to troubleshoot building wxmac, it's enough of a headache figuring out what is going on with my system much less anyone else's. Use the homebrew build (which is what the distribution uses).
> 
> https://formulae.brew.sh/formula/wxmac

I did exactly what was written in the developer documentation for slic3r. To fix the bug need fix the build process or fix the build manual. Not just close the bug. :)
