### ISSUE TITLE
how to change the comment shown for LineEdit

### ISSUE THREAD

**Issue by farhadcomp** [slic3r/Slic3r#4735]
Hi,
I'm going to change the descriptions that appear when hover the mouse on LineEdits but can't find where is the code of these descriptions:
![capture](https://user-images.githubusercontent.com/39711597/52523331-72dfb400-2ca5-11e9-8830-92af6ccbe0d6.JPG)
can anyone help me to change these descriptions plz?
Thanks in advance

**Comment by supermerill** [comment]
printconfig.cpp, in xs/src/libslic3r


```
    def = this->add("default_print_profile", coString);
    def->label = __TRANS("Default print profile");
    def->tooltip = __TRANS("Default print profile associated with the current printer profile. "
                   "On selection of the current printer profile, this print profile will be activated.");
    def->default_value = new ConfigOptionString();
```

here, modify the 3rd-4th lines
