### ISSUE TITLE
problem on loading slic3r.exe

### ISSUE THREAD

**Issue by farhadcomp** [slic3r/Slic3r#4736]
hi everyone,
when I made a zip file as it was said in [https://github.com/slic3r/Slic3r/wiki/Running-Slic3r-from-git-on-Windows](url) I got a message: "can not find freeglut.dll" but after that it created zip file without any errors:
![capture](https://user-images.githubusercontent.com/39711597/52575999-85d4be80-2e34-11e9-8738-0bde0090d33e.JPG)

but my problem is when I doubled click on slic3r.exe from unpacked zip folder,  nothing happened and slic3r don't open. here is unpacked zip folder:
![capture](https://user-images.githubusercontent.com/39711597/52576652-c3861700-2e35-11e9-8ed6-5b373e2983da.JPG)

so what is the problem? does it happen just because of missing freeglut.dll?

**Comment by lordofhyphens** [comment]
You're missing freeglut.dll, which is available online (it's an open-source library and not strictly part of slic3r).

**Comment by lordofhyphens** [comment]
Note that CLI slicing will still work, freeglut is just a requirement for the GUI
