### ISSUE TITLE
After Win10-update on Feb 13th slic3r opens and works extremely slow. 

### ISSUE THREAD

**Issue by cypcyp51** [slic3r/Slic3r#4739]
On win10 1809 slic3r 1.3.0 as well as older 1.2.9 works extremely slow, opening until 
menu items appear can last up to 20 sec. All steps lag extremely. Happened since yesterday Feb 13th (MS-Patchday)
After removal of the update KB4481031 and KB83452 slic3r 1.3.0 workes fine again.

**Comment by cypcyp51** [comment]
Sorry, published the question before finishing. After removal of the update KB4481031 slic3r 1.3.0 worked fine again until the update installs again.

**Comment by supermerill** [comment]
Last time it was the graphic drivers. See if windows doesn't update/downgrade your driver with the update. Or just install a good one.

**Comment by cypcyp51** [comment]
Already looked at the graphics driver, seem to be fine, it's the intel HD Graphics 4000 from Dec 21. 2015, so nothing has changed

**Comment by cypcyp51** [comment]
Meanwhile i checked intel for new graph drivers and installed the driver dated Aug 16th, 2018. Since i have to work with slic3r today, i have blocked the re-installation of updates. As soon as i have time left i will retry with the new updates for win10 again. 
On my notebook with win10 1803 the updates from Feb 13th seem to have no effect on the program.

**Comment by lordofhyphens** [comment]
Odd, KB4481031 should have zero effect (it was a .NET update, which Slic3r doesn't use).

The other KB isn't the full string so I don't know what it is.

**Comment by cypcyp51** [comment]
Sorry, had forgotten to enter 2 digits, KB4483452, was also .NET update. Probably i fooled myself with the de-installed updates.
Meanwhile i have installed all updates again for test purposes - und all works fine again - so far.
Probably the outdated Intel graphs driver didn't want to work with some other update features.
Thanks a lot for the hints.
