### ISSUE TITLE
Slic3r takes a very long time to build

### ISSUE THREAD

**Issue by marcel2034** [slic3r/Slic3r#4745]
**Bug description**
Slic3r is very fast to build with the C++ method 
```
mkdir build  
cd build   
cmake ../src/   
cmake --build . -- -j4   
```
 but ./slic3r returns unknown exception 
as in issue : [4719](https://github.com/slic3r/Slic3r/issues/4719). 

When building with perl, slic3r runs, but it takes a very long time (15 min) to build, even with small modifications. (If I want to play with the code, it won't be viable)

Is there something I'm missing ? 
Can I boost perl building ? 
Should I be able to run slic3r with just the C++ side ? 

**System**
- OS: Ubuntu
- Version 18.04
- 1.3.0-1302-g05a2f902

**Comment by supermerill** [comment]
it's because, with perl, you rebuild everything each time.

After a full build, if you only do a small modification in a source file, you can:

cd xs
./build install


i think you also need to export something for this to work, but i don't remember what.

**Comment by lordofhyphens** [comment]
@supermerill you need to manually set local::lib path (see local::lib documentation on cpan)

**Comment by marcel2034** [comment]
@supermerill  @lordofhyphens Thanks for replying ! 
I'm not sure I understand where to set the local::lib path. 

I tried to add the local::lib command in .bashrc : 
```eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"```
but it doesn't seem to work. 

I can `./Build install` in xs folder, but the code changes don't appear in the execution of slic3r.

**Comment by lordofhyphens** [comment]
eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=/path/to/slic3r/local-lib)"

**Comment by ben2034** [comment]
It worked :) 
Thank you very much !

**Comment by marcel2034** [comment]
It worked :) 
Thank you very much !
