### ISSUE TITLE
Copy the Estimated printing time result to the Print Summary screen

### ISSUE THREAD

**Issue by thiagopeixoto16** [slic3r/Slic3r#4758]
Currently this information is only being displayed at **Controller tab** when printing via USB (queue frame).
My suggestion is to copy that field to the **Print Summary** screen for those don't print via USB:
![image](https://user-images.githubusercontent.com/4227271/54140834-3ff32200-4403-11e9-91a0-220948738df2.png)

**Comment by leonplust** [comment]
Is anyone working on this already? if no, I would start to work on this.

**Comment by thiagopeixoto16** [comment]
@leonplust I'm not working on this. 
...because I'm a humble poor user :)

**Comment by shepherdsnowdev** [comment]
+1 request for this!

**Comment by supermerill** [comment]
+1, you can start working on it.

**Comment by lordofhyphens** [comment]
Thank you to @l29ah for knocking this out.

**Comment by thiagopeixoto16** [comment]
@l29ah Thank you very much:
![image](https://user-images.githubusercontent.com/4227271/57166992-64032c00-6dd2-11e9-94cc-1e3b39dd4d5a.png)
