### ISSUE TITLE
cppgui Aborted (core dumped)

### ISSUE THREAD

**Issue by EitanSomething** [slic3r/Slic3r#4784]
when I run the cppgui of slic3r I get the error 

>  terminate called after throwing an instance of 'Slic3r::UnknownOptionException'
>    what():  std::exception
> Aborted (core dumped)

when I run  cmake ../src 

> The C compiler identification is GNU 7.3.0
> -- The CXX compiler identification is GNU 7.3.0
> -- Check for working C compiler: /usr/bin/gcc
> -- Check for working C compiler: /usr/bin/gcc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/g++
> -- Check for working CXX compiler: /usr/bin/g++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Boost version: 1.65.1
> -- Found the following Boost libraries:
> --   system
> --   thread
> --   filesystem
> --   chrono
> --   date_time
> --   atomic
> -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
> -- Found wxWidgets: -L/usr/lib/x86_64-linux-gnu;-pthread;;;-lwx_baseu_net-3.0;-lwx_gtk3u_gl-3.0;-lwx_gtk3u_html-3.0;-lwx_gtk3u_aui-3.0;-lwx_gtk3u_adv-3.0;-lwx_gtk3u_core-3.0;-lwx_baseu-3.0 (found version "3.0.4") 
> wx found!
> OpenGL found!
> 

 - OS: Linux Ubuntu 18.04

**Comment by lordofhyphens** [comment]
Duplicates #4719
