### ISSUE TITLE
No --export-stl option in CLI version

### ISSUE THREAD

**Issue by yablokoff** [slic3r/Slic3r#4785]
Version 1.3.0 or 1.3.1-dev Mac and Linux both.

In User Manual (https://manual.slic3r.org/advanced/command-line) it's said there's an option `--export-stl` which should convert given file to STL. My goal is to convert 3MF file for STL for example.

Terminal command `slic3r` fails with "Unknown option: export-stl".
I tried compiled versions and one compiled from source code.

"Export to STL" works perfectly in GUI version.

How to launch this in terminal version?

**Comment by lordofhyphens** [comment]
@yablokoff it's part of the new C++-based CLI. There are no plans to implement it in the perl CLI.
