### ISSUE TITLE
slicer crashes when deleting post script

### ISSUE THREAD

**Issue by RaabenFuchs** [slic3r/Slic3r#4787]
hello again,
i like slicer very much, and would like to improve some minor bugs on myself, as soon as i manage to perform an own build.
i have some circumstances where slicer always crashes, this is one occurance:

win 10, v1.3.0

when i delete the path to the postprocessing script in "print settings" slicer crashes -> im not able to disable the script completely

**Comment by foreachthing** [comment]
See #4323 as well.
You have to remove it in the settings file.

**Comment by RaabenFuchs** [comment]
Ah thx!

very interesting. this explains much. thx
