### ISSUE TITLE
slic3r not rendering correctly this file

### ISSUE THREAD

**Issue by swolter1975** [slic3r/Slic3r#4792]
### Do not report Prusa3D Slic3r bugs here without confirming it is a problem on a development release of Slic3r, or your issue will be closed. [Development builds of Slic3r](https://dl.slic3r.org/dev). [Prusa3D Issue Tracker](https://github.com/Prusa3D/Slic3r/issues)

**Describe the bug**
Slic3r is not rendering correctly a file stl

**To Reproduce**
1. Go to file-open and ipen the attached file i send, is just an STl which is not being rendered properly.

**3D Model and Slic3r Configuration Export**
Attached zip file with STl file used.
[UpperArm - Finger slider-export.zip](https://github.com/slic3r/Slic3r/files/3113799/UpperArm.-.Finger.slider-export.zip)

**Expected behavior**
THe file shall be rendered correclty on both sides.

**Screenshots**
![error-stl](https://user-images.githubusercontent.com/49459536/56672575-4a4c4100-667c-11e9-9d7f-53e42e9feab7.jpg)

**Desktop (please complete the following information):**
 - OS: [WINDOWS 10
 - Version 1.3.1 dev AND 1.3.0
     - _Do not report Prusa3D Slic3r bugs here without confirming it is a problem on a development release of Slic3r, or your issue will be closed. *Only* use normal Slic3r version IDs._
     - _For -dev versions, use `git describe --tag` or get the hash value for the version you downloaded or `git rev-parse HEAD`_
     - _Use `About->About Slic3r` for release versions._

**Additional context**
my config file attached (for anet a8 settings printer):

[config.zip](https://github.com/slic3r/Slic3r/files/3113048/config.zip)

[UpperArm - Finger slider-export.zip](https://github.com/slic3r/Slic3r/files/3113798/UpperArm.-.Finger.slider-export.zip)

**Comment by VanessaE** [comment]
Your report is incomplete.

Please embed screenshots (not as a proprietary document), add OS and Slic3r release info, and your config.

**Comment by swolter1975** [comment]
i have updated the report please review it thank you.

**Comment by VanessaE** [comment]
Please add the STL file.

**Comment by swolter1975** [comment]
added as zip file thanks

**Comment by foreachthing** [comment]
Your STL is faulty.
Use https://service.netfabb.com/ to fix it.

![image](https://user-images.githubusercontent.com/10420187/56689385-3e439c00-66db-11e9-8c16-7223671bfa75.png)
Selected: fixed. Yours in cyan, the faulty one.

Also, what CAD have you used to draw this? Or, try to increase accuracy with your STL-export:
![image](https://user-images.githubusercontent.com/10420187/56689540-98446180-66db-11e9-91bf-924bf54444c8.png)

**Comment by VanessaE** [comment]
Good eye, @foreachthing.

**Comment by swolter1975** [comment]
Gilbert

thanks for your reply. its weird because i opened the STL file on idea
maker, also in cura and in both it opened well, the only program where it
does not load well was slic3r.
so n not sure 100% what the probem weas. i did not produce the stl file i
just downloaded from the web.

thank you anyways

rgds,

sw

**Comment by lordofhyphens** [comment]
@swolter1975 that other programs open a garbage file doesn't mean much if the file is indeed garbage, just that their edge cases work out differently than us.
