### ISSUE TITLE
Elephant Foot Compensation

### ISSUE THREAD

**Issue by Tillema** [slic3r/Slic3r#4801]
When I slice without perimeters, overlap and with elephant foot compensation, the compensation is applied to all bottom solid layers. When I set it to 3, the first 3 layers are smaller than the following, due to the elephant compensation. Why? I thought this would be suitable for the very first layer. Why are the following 2 solid bottom layers also concerned by the elephant foot compensation?

Relevant settings:
Layer heights: 0.2mm
Solid bottom layers: 3
Fill angle: 0deg
Fill density: 100% Rectilinear
Extrusion widths: 0.5mm
Infill/perimeters overlap: 0%
Elephant foot compensation: 0.1mm
Extrusion multiplier: 100%
Nozzle diameter: 0.4mm

Note: I'm using Slic3r PE 1.41.3 win64. Does it makes sense?

**Comment by lordofhyphens** [comment]
We don't have this feature implemented (#4750).

Please report this issue at Prusa3d/Slic3r issue tracker, not here.
