### ISSUE TITLE
Rotate Axis Color menu coding

### ISSUE THREAD

**Issue by 3dprinter3** [slic3r/Slic3r#4803]
Could you please color code the Object > Rotate
Make the "Around X axis" green
Make the "Around Y axis"  Blue
Make the "Around Z axis" Red

It would really help for those not every day users

Thanks Mike

**Comment by VanessaE** [comment]
Traditionally, X is red, Y is green, and Z is blue, and Slic3r already uses those colors:
![image](https://user-images.githubusercontent.com/1733537/57184258-0bda3180-6e87-11e9-9745-3238508c7ca1.png)

**Comment by lordofhyphens** [comment]
Also it matches the colors of the axes.
