### ISSUE TITLE
libslic3r python binding

### ISSUE THREAD

**Issue by amarschn** [slic3r/Slic3r#4804]
Hi all,

Does anyone know if there are any python bindings or wrappers for libslic3r? I haven't found anything online but I figured I would ask here.

For a little context, I am working on a slicer codebase that is largely python, but I would like to avoid reinventing the wheel and be able to use libslic3r for its speed and reliability. Any help is appreciated.

Thanks,
Drew

**Comment by lordofhyphens** [comment]
@amarschn No, you should be able to knock something together with SWIG w/o too much headache (pattern it after the perl XS stuff). If you do, we'll take a PR to add it to the main repo and you will have my gratitude.
