### ISSUE TITLE
Slic3r crashs loading STL

### ISSUE THREAD

**Issue by ilovelinux** [slic3r/Slic3r#4805]
**Describe the bug**
I need to print the gears of this package: https://www.thingiverse.com/thing:974906
When I load the STL file, Slic3r crashes. This is the output:
```
$ slic3r
realloc(): invalid next size
Aborted (core dumped)
```
I also tried to fix the .stl file with `slic3r --repair` but it doesn't work too.

**To Reproduce**
1. Go to 'https://www.thingiverse.com/thing:974906'
2. Download and unzip files
3. Open _gears.stl_

**3D Model and Slic3r Configuration Export**
[issue.zip](https://github.com/slic3r/Slic3r/files/3167614/issue.zip)

**Expected behavior**
Open STL file

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version 1.3.0 (installed by [AUR](https://aur.archlinux.org/packages/slic3r/))

**Comment by lordofhyphens** [comment]
Make sure you pass the model through netfabb or something similar.

**Comment by lordofhyphens** [comment]
Interestingly, doesn't crash when running through the CLI.
[gears-gcode.zip](https://github.com/slic3r/Slic3r/files/3193613/gears-gcode.zip)

**Comment by lordofhyphens** [comment]
I have a workaround submitted in a pull request so you can see the model in all of its terrible glory.
