### ISSUE TITLE
Speed weirdness

### ISSUE THREAD

**Issue by kajsilander78** [slic3r/Slic3r#4816]
1. Set all print speeds to 15mm/s
2. Slice a 20mm small coin, 3mm high
3. Notice the speed increase at 2nd layer after printing perimeters....same thing with top infill.

Dont know if extrusion is scaled to match speed, printed tpu when I noticed this. Got massive underextrusion, but it could be extruder limitation.

[files.zip](https://github.com/slic3r/Slic3r/files/3220942/files.zip)

**Comment by lordofhyphens** [comment]
Is there a config export in that zip?

**Comment by kajsilander78** [comment]
yep

**Comment by kajsilander78** [comment]
![Screenshot at 2019-05-26 19-51-30](https://user-images.githubusercontent.com/25552425/58385377-bad5dd00-7fef-11e9-996c-c71a4641c59a.png)

**Comment by kajsilander78** [comment]
Tried both nightly and 1.3 and think I found the issue. Bridge speed is 60mm/s! That seems to set top layer speed.....

**Comment by lordofhyphens** [comment]
Just looking at the second layer indicates that Slic3r is treating that infill like it's a bridge.

**Comment by lordofhyphens** [comment]
Here's 0.1 flow ratio for bridges (which Slic3r will show a preview for)
![image](https://user-images.githubusercontent.com/31754/58385502-08822380-7fb7-11e9-9ca7-0a71d726871e.png)

Same layer, 1.0:
![image](https://user-images.githubusercontent.com/31754/58385508-2059a780-7fb7-11e9-9363-8288618cd582.png)

**Comment by kajsilander78** [comment]
Oh, thought bridges only was for bridges... Wanted some stretch for tpu bridges...and was experimenting with bridgespeed and flow for bridges when I ran into this issue. ;) Tried changing nozzle and calibrating extruder and so on.....

**Comment by lordofhyphens** [comment]
It's for anything that would act like a bridge. I don't know why that specific layer is presenting as a bridge though (verbose gcode doesn't indicate it should be).

**Comment by lordofhyphens** [comment]
Remember that % in width is over layer height, not default extrusion width.
