### ISSUE TITLE
Command Prompt Not Working

### ISSUE THREAD

**Issue by vatansbeytr** [slic3r/Slic3r#4831]
**Describe the bug**
Command console can't open when I try to run  at the command prompt "slic3r-console.exe"
 but program opening not console.

**Comment by lordofhyphens** [comment]
Can't reproduce. What are you trying to do?

![image](https://user-images.githubusercontent.com/31754/60144317-83418880-9787-11e9-93c2-0f0431a7378c.png)

**Comment by lordofhyphens** [comment]
`slic3r-console.exe` just keeps the background console open when you run it, which it just did for me. 

If you invoke it w/o a path to a STL it will pop up the GUI, as intended.

**Comment by vatansbeytr** [comment]
I want to work with console, but I can't slice when I write slic3r-console.exe program pop up and I can't write anything to console

**Comment by lordofhyphens** [comment]
It's not a console you type in, it's just there to show you info output from the slicer.

**Comment by lordofhyphens** [comment]
Use `slic3r-console.exe --help` to get command line options.
