### ISSUE TITLE
Slicing error?? Model gets 33 solid layers where none should exist

### ISSUE THREAD

**Issue by rmpel** [slic3r/Slic3r#4839]
**Describe the bug**
Don't know if this is a bug. It's reproducible on version 1.3.0 and 1.3.1 dev, and I cannot figure out what to do about it. Cura slices correctly so I know the model is (as far as I can tell) o.k.

**To Reproduce**
using 5f68ce4:
1. open model
2. slice
3. sliced model is wrong

using 8adf792:
1. open model
2. slice
3. slicing fails!

**3D Model and Slic3r Configuration Export**
[Archive.zip](https://github.com/slic3r/Slic3r/files/3390038/Archive.zip)

**Expected behavior**
Model should print hollow, gets 7mm plastic instead :(

**Screenshots**
<img width="1680" alt="Screenshot 2019-07-14 at 16 48 43" src="https://user-images.githubusercontent.com/1086776/61185308-01db6880-a658-11e9-975a-fc06579e0d51.png">

with 1.3.1-dev-5f68ce4:
<img width="1699" alt="Screenshot 2019-07-14 at 16 49 36" src="https://user-images.githubusercontent.com/1086776/61185312-03a52c00-a658-11e9-9328-2ee0423e5f9a.png">

with 1.3.1-dev-8adf792
<img width="1699" alt="Screenshot 2019-07-14 at 16 59 03" src="https://user-images.githubusercontent.com/1086776/61185361-ca20f080-a658-11e9-9465-c280811df3cf.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.5
 - Version 1.3.0, 1.3.1-dev-5f68ce4, 1.3.1-dev-8adf792

**Comment by lordofhyphens** [comment]
That model is garbage. 
![image](https://user-images.githubusercontent.com/31754/61587398-737f4f00-ab4f-11e9-8613-c8a8f77c47d8.png)
There's a hint that maybe the model is actually garbage and needs repair. 

Running the model through [Netfabb online service](https://service.netfabb.com/service.php)
produced [PETcoupler_fixed.zip](https://github.com/slic3r/Slic3r/files/3414320/PETcoupler_fixed.zip)
which sliced like so:

![image](https://user-images.githubusercontent.com/31754/61587428-f43e4b00-ab4f-11e9-8cc3-cd32532a5761.png)
