### ISSUE TITLE
Can't change Perimeter Overhang speed because Bridges settings is grayed out

### ISSUE THREAD

**Issue by zapta** [slic3r/Slic3r#4842]
**Describe the bug**
Print Settings | Speed | Bridges is grayed out in some conditions, even though it's actually affects the slicing results. This makes tweaking the speed impossible.

**To Reproduce**
1. Load Calicat model from thingiverse  https://www.thingiverse.com/thing:1545913/files
2. Set top and bottom layer counts to 0.
3. Set shell perimeters to 1
4. Set infill to 0%
5. Slice and review the results using Feature Type color mapping
6. Verify that the face of the cat has some Overhang Perimeter type lines
7. Switch the slicing review to Speed color mapping.
8. Now try to change the speed of the Overhang Perimeter lines. Notice that Print Settings | Speed | Bridges is grayed out and don't accept changes.

Actual behavior:  Under the above conditions, Print Settings | Speed | Bridges is grayed out

Expected behavior: Print Settings | Speed | Bridges should be active and allows the user to change Overhang Perimeter speed since it appears in the slicing results.

**Comment by lordofhyphens** [comment]
This is controlled in the GUI at https://github.com/slic3r/Slic3r/blob/master/lib/Slic3r/GUI/PresetEditor.pm#L920

With no infill layers, or top/bottom solid layers, it's very specific pathological examples that would have bridge speed.

**Comment by lordofhyphens** [comment]
Looks like the only other place that it affects is overhang perimeters.

**Comment by zapta** [comment]
Thanks for looking into it. BTW, if both overhang and perimeter overhang use the same settings, what is the reason for presenting them to the user as two different line types?

**Comment by zapta** [comment]
(I didn't intend to close. Just clicked the wrong button)

**Comment by lordofhyphens** [comment]
Don't know offhand, as it was like that before I got onto the project.

**Comment by zapta** [comment]
Thanks everybody for the quick resolution.
