### ISSUE TITLE
New Icon proposal

### ISSUE THREAD

**Issue by stockHuman** [slic3r/Slic3r#4898]
Hello good people,

I'd like to propose a fresh coat of paint on the app icon. See it right here:
<p align="center"><img src='https://user-images.githubusercontent.com/13852458/69979454-59417e80-14fc-11ea-8742-32758c186997.png'></p>

And here with context, next to blender and a custom icon for the fork of CNCjs by SnapMaker.

![Screen Shot 2019-12-02 at 11 55 54 AM](https://user-images.githubusercontent.com/13852458/69979560-842bd280-14fc-11ea-836b-c178b756739c.png)

If the emerald green is too far a departure from the original icon, I could tone it down - though I find it works next to other icons and on its own. The rationale for the change was the icon not really fitting with the rest of my system's icons, and being somewhat hard read, visually speaking. 

Test it out for yourselves with [icns](https://github.com/slic3r/Slic3r/files/3912407/slic3r.icns.zip), <a href="https://github.com/slic3r/Slic3r/files/3912393/favicon.ico.zip" download>ico</a> or <a href="https://user-images.githubusercontent.com/13852458/69980202-c3a6ee80-14fd-11ea-99cd-b29dec443cb5.png" download>a large png</a>.

Or render it out on fellow [FOSS software](https://github.com/slic3r/Slic3r/files/3912403/slic3r.blend.zip).

Thanks!

**Comment by foreachthing** [comment]
I like it "flat", like the Blender one. But I like the emerald colors a lot! :-)

**Comment by stockHuman** [comment]
Thanks for your input! :) I tried flat designs on the original icon, but going from 'cartoon' to flat on a sliced sphere effectively makes it two half circles - and that's why I went with the rendered polyhedron. Anyway, here are some flat designs - with more and less pronounced offsets in the slices. I find the first one most effective of the flat ones.


<img src="https://user-images.githubusercontent.com/13852458/70060862-46d54c80-15b1-11ea-8046-40813777c460.png" height="200" alt="dramatic flat"/>  <img src="https://user-images.githubusercontent.com/13852458/70060879-4c329700-15b1-11ea-8bac-3a7eeec67407.png" height="200" alt="less dramatic flat"/> <img src="https://user-images.githubusercontent.com/13852458/70060874-4a68d380-15b1-11ea-8def-ec373527237a.png" height="200" alt="dramatic flat in circle"/>

**Comment by lordofhyphens** [comment]
@alranel opinions?

**Comment by VanessaE** [comment]
I dunno about him, but in *my* opinion :smile: the proposed image (whichever of the four is desired) ought be supplied as a themed icon via `/usr/share/icons/FOO` for whatever theme `FOO` best matches the given style (or however that works on non-*nix platforms).

Slic3r's existing icon can then become the `hicolor` standard image, or whatever passes for the "fallback" icon if no themed image is provided.

Either that or make it a local user override.

(See also the discussion on IRC)
