### ISSUE TITLE
no second range for object layers

### ISSUE THREAD

**Issue by jorigel** [slic3r/Slic3r#4902]
hi,

running into problems of opening new ranges for object layers.

using:
Version: 2.1.0+linux64
Build: PrusaSlicer-2.1.0+linux64-201909160925
Operating System: Unix
System Architecture: 64 bit
System Version: Linux 5.3.0-24-generic x86_64
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
running a xfce-desktop

Resident memory: 536MB
Shared memory: 62MB
Private memory: 474MB
Peak memory usage: 647MB
RAM size reserved for the Undo / Redo stack: 821MB
RAM size occupied by the Undo / Redo stack: 0MB
OpenGL installation
GL version: 3.0 Mesa 19.2.1
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Haswell Desktop 
GLSL version: 1.30

the problem is:
After opening the layers section of an object everything is possible for the given range. As soon as I try to open an additional range this is not possible because there is no add or delete button behind the 'settings for height range'. So, no more ranges -> no possibilities to set colors or other.

Playing around with window themes or screen resolution has no influence, because the column for that window is obviously fixed. So it doesn't matter how much space available for the complete window, the space for the column stays too narrow. I don't see any chance for me to make these buttons visible . . . 

looks like this:
![grafik](https://user-images.githubusercontent.com/5578691/70379478-7972a280-192d-11ea-8892-cf723ffd4a73.png)

possible solution:
could be to open an additional range as soon as the 'height range modifier' in the object's editing menu is chosen a second time and so on. It makes as much sense as opening the range the first time at that place and it would circuit around the prob.

thanx for Your attention

**Comment by lordofhyphens** [comment]
Wrong slicer. This is not a support forum for prusaslicer
@bubnikv
