### ISSUE TITLE
Top and bottom layer craziness with adaptative layer quality activated

### ISSUE THREAD

**Issue by guidugast** [slic3r/Slic3r#4920]
### Behavior
on top and bottom layer, when using adaptative quality , the layer height evolves as it should (I presume) but I also get a layer thickness evolution that is weird:
only the very top and bottom layers has 100% width, but the 3 others (out of 4 in my configuration if I remember, or maybe 2 out of 3 top/bottom layers...) has a very small width (see in the sliced file).

What is it happening?

[top+bottom_layer_crazyness.zip](https://github.com/slic3r/Slic3r/files/4081293/top%2Bbottom_layer_crazyness.zip)

#### STL/Config (.ZIP) where problem occurs
_Upload a zipped copy of an STL and your config (`File -> Export Config`)_

**Comment by lordofhyphens** [comment]
Is your issue resolved
