### ISSUE TITLE
Anycubic Mega X

### ISSUE THREAD

**Issue by Priterman1234** [slic3r/Slic3r#4953]
Good Afternoon, I am in need of some help with this program Sli3er.I have a Anycubic Mega X and would like to start printing from sli3er with the Mega X.Can anybody tell me what settings I should use and basically where to start.

Thanks

Neil_

**Comment by lordofhyphens** [comment]
Https://manual.slic3r.org

Should be the same as most other printers.
As for settings, that's a magical journey for you to undertake with the aid of people who also have that printer.
