### ISSUE TITLE
Custom path planning algorithms

### ISSUE THREAD

**Issue by SmartFactory-github** [slic3r/Slic3r#4962]
I am trying to apply new path planning algorithms to connect the internal contour trajectory with the infill path trajectory, in order to reduce the printing time and increase fiber's composite resistance.

I have not been able to identify which files I must edit from the directory libslic3r. Also I haven't been able to find documentation from this .hpp and .cpp.

I would thank any advice/recommendation, and until the day it is working, I  will upload a tutorial to how to make these changes.

thanks in advance.

Sergio Salinas.

**Comment by lordofhyphens** [comment]
Start your investigation around Layer, its methods, and the things that use it. This data structure holds the slices in Z.

https://github.com/slic3r/Slic3r/blob/master/xs/src/libslic3r/Layer.hpp

Layers are processed through https://github.com/slic3r/Slic3r/blob/master/xs/src/libslic3r/PrintGCode.cpp in paralle.


May be related to your interests:
https://github.com/slic3r/Slic3r/blob/master/xs/src/libslic3r/MotionPlanner.hpp
https://github.com/slic3r/Slic3r/blob/master/xs/src/libslic3r/MotionPlanner.cpp

Extending the doxygen documentation would be very helpful: 
https://manual.slic3r.org/libslic3r-doc/
