### ISSUE TITLE
HELP: How to use libslic3r in my C++ Application

### ISSUE THREAD

**Issue by foron23** [slic3r/Slic3r#4966]
Hi everyone, 
I'm currently thinking on developing a project which would consist on an Slic3r fork with a custom GUI made by me, developed in Qt.
My aim is to use the slicing backend provided by libslic3r, however, i cannot manage to integrate the sources from xs/src into my project.
Any ideas on how could I achieve this?

Thanks in advance.

**Comment by lordofhyphens** [comment]
Take a look at src/CMakeLists.txt for the general library. I have zero interest in encouraging forks so glhf. 

Closing.
