### ISSUE TITLE
Slic3r adding defective additional filling layer inside the object

### ISSUE THREAD

**Issue by FPrefect20** [slic3r/Slic3r#4971]
**Describe the bug**
When slicing the enclosed cone object an 0.2mm filling layer is added inside the object and the object is closed with 1 layer filament.

**To Reproduce**
1. Open the enclosed object with slic3r
2. Rotate with "3d view" to have a look inside (there's no filling inside)
3. Click on "preview"
4. After the slicing completes the additional layer can be observed inside the object

**3D Model and Slic3r Configuration Export**
[slic3r cone.zip](https://github.com/slic3r/Slic3r/files/4652229/slic3r.cone.zip)

**Expected behavior**
No additional filling added

**Screenshots**
![image](https://user-images.githubusercontent.com/65475741/82360268-6e0dc200-9a09-11ea-95e8-f0961520e533.png)

Printing:
![image](https://user-images.githubusercontent.com/65475741/82360992-7dd9d600-9a0a-11ea-96fc-ac465bfa28e3.png)

**Desktop (please complete the following information):**
 - Windows 10  64Bit
 - Version 1.3.0

**Comment by lordofhyphens** [comment]
https://dl.slic3r.org/dev/win can you reproduce with 1.3.1-dev?

**Comment by FPrefect20** [comment]
Yes, same problem.

![image](https://user-images.githubusercontent.com/65475741/82391751-60286300-9a42-11ea-995d-5babc129aa06.png)

**Comment by lordofhyphens** [comment]
Thanks. One more sanity check: did you pass the model through https://service.netfabb.com/service.php

**Comment by FPrefect20** [comment]
Although other slicer software doesn't show the "additional filling layer" problem the fixing with "netfabb" indeed seems to solve the problem. In the "preview" of Slic3r the object is shown correct now.
I will print the object again to double check the result.
Thank you!!!
