### ISSUE TITLE
_GLIBCXX_USE_C99 is not meant for you to define

### ISSUE THREAD

**Issue by jwakely** [slic3r/Slic3r#4975]
The `xs/Build.PL` script adds `-D_GLIBCXX_USE_C99` to the compiler flags, which results in undefined behaviour. That is an internal macro defined and used by libstdc++ and you must not set it yourself.

If it isn't already defined correctly by libstdc++ then defining it isn't going to help, because it will make libstdc++ try to use functions which aren't actually present in the C library.

**Comment by lordofhyphens** [comment]
Go ahead and submit a PR for it.
