### ISSUE TITLE
Centering the title 

### ISSUE THREAD

**Issue by wiwiB** [slic3r/Slic3r#4979]
### Version
HI , i am a new user of the slic3r , i need help . how can  i change the format of the title of the main window ( center it , make it bold ... ) 
Thank you 
![Capture](https://user-images.githubusercontent.com/66416708/84134968-42e32500-aa41-11ea-9e85-badc045223d8.PNG)

**Comment by lordofhyphens** [comment]
https://docs.wxwidgets.org/3.0/classwx_window.html

Consult the underlying GUI framework documentation. There is not an option in Slic3r to do such a thing and I will never accept a PR to add it.

**Comment by wiwiB** [comment]
i know i am just trying to undrestand how the layout of the main Frame changes
