### ISSUE TITLE
Linux Slic3r shell script doesn't detect DIR variable properly

### ISSUE THREAD

**Issue by OrenVo** [slic3r/Slic3r#5033]
**Describe the bug**
Cannot run slic3r from another directory. The line BIN=$(readlink "$0") doesn't fill BIN variable when path to script is not symlink.

**To Reproduce**
Run Slic3r script from different directory.

**Expected behavior**
Slic3r runs.

 - OS: Linux opensuse tumbleweed
 - Version 1.3.0

**Additional context**
I didn't add Slic3r script to PATH variable. I run the script as /path/to/Slic3r

**Solution**
I added DIR=/path/to/

**Comment by lordofhyphens** [comment]
This was already fixed with the following script from #4266

https://github.com/slic3r/Slic3r/commit/dc9d7ed70fa0fa505ddba59470899241e6676ea6

```bash
#!/bin/bash

BIN=$(readlink -f "$0")
DIR=$(dirname "$BIN")
export LD_LIBRARY_PATH="$DIR/bin"
exec "$DIR/perl-local" -I"$DIR/local-lib/lib/perl5" "$DIR/slic3r.pl" "$@"

```
