### ISSUE TITLE
make (e=2): The system cannot find the file specified.

### ISSUE THREAD

**Issue by godeye** [slic3r/Slic3r#5035]
**we are building with cmake & vs 2017 on windows 64 bit**

show this :

> 
> Detecting C compiler ABI info failed to compile with the following output:
> Change Dir: C:/vagrant/slic3r/src/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):C:/vagrant/mingw/mingw64/bin/mingw32-make.exe cmTC_661ce/fast && C:/vagrant/mingw/mingw64/bin/mingw32-make.exe  -f CMakeFiles\cmTC_661ce.dir\build.make CMakeFiles/cmTC_661ce.dir/build
> 
> mingw32-make.exe[1]: Entering directory 'C:/vagrant/slic3r/src/CMakeFiles/CMakeTmp'
> 
> process_begin: CreateProcess(NULL, \vboxsvr\vagrant\cmake-3.19.1-win64-x64\bin\cmake.exe -E cmake_echo_color --switch= --progress-dir=C:\vagrant\slic3r\src\CMakeFiles\CMakeTmp\CMakeFiles --progress-num=1 "Building C object CMakeFiles/cmTC_661ce.dir/CMakeCCompilerABI.c.obj", ...) failed.
> 
> make (e=2): The system cannot find the file specified.
> 
> 
> mingw32-make.exe[1]: *** [CMakeFiles\cmTC_661ce.dir\build.make:83: CMakeFiles/cmTC_661ce.dir/CMakeCCompilerABI.c.obj] Error 2
> 
> mingw32-make.exe[1]: Leaving directory 'C:/vagrant/slic3r/src/CMakeFiles/CMakeTmp'
> 
> mingw32-make.exe: *** [Makefile:139: cmTC_661ce/fast] Error 2
> 
> 
> 
> 
> 
> Determining if the C compiler works failed with the following output:
> Change Dir: C:/vagrant/slic3r/src/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):C:/vagrant/mingw/mingw64/bin/mingw32-make.exe cmTC_731f1/fast && C:/vagrant/mingw/mingw64/bin/mingw32-make.exe  -f CMakeFiles\cmTC_731f1.dir\build.make CMakeFiles/cmTC_731f1.dir/build
> 
> mingw32-make.exe[1]: Entering directory 'C:/vagrant/slic3r/src/CMakeFiles/CMakeTmp'
> 
> process_begin: CreateProcess(NULL, \vboxsvr\vagrant\cmake-3.19.1-win64-x64\bin\cmake.exe -E cmake_echo_color --switch= --progress-dir=C:\vagrant\slic3r\src\CMakeFiles\CMakeTmp\CMakeFiles --progress-num=1 "Building C object CMakeFiles/cmTC_731f1.dir/testCCompiler.c.obj", ...) failed.
> 
> make (e=2): The system cannot find the file specified.
> 
> 
> mingw32-make.exe[1]: *** [CMakeFiles\cmTC_731f1.dir\build.make:83: CMakeFiles/cmTC_731f1.dir/testCCompiler.c.obj] Error 2
> 
> mingw32-make.exe[1]: Leaving directory 'C:/vagrant/slic3r/src/CMakeFiles/CMakeTmp'
> 
> mingw32-make.exe: *** [Makefile:139: cmTC_731f1/fast] Error 2

**Comment by lordofhyphens** [comment]
Not seeing anything here that looks like a issue with Slic3r.

Looks to me like you misconfigured CMake and/or are using the wrong generator.
