### ISSUE TITLE
Tempurature of hotend not set in gcode

### ISSUE THREAD

**Issue by jmger** [slic3r/Slic3r#5044]
Hi all,
I used to use simplify3d, now I am using Slic3r. I moved to using the 1.3.1 developer version. To many issues with version 1.3.0. When I set the Temp of the Extruder under the Filament tab this value does not get added to the gcode output file. I checked/ticed the setting "Use Set and Wait gcode" under the Printer tab. But the gcode is not being added to my gcode file. Bed temp is being added correctly. For now as a work around I add M109 S245 to my starting gcode script. Is this issue going to be fixed?

Thank You
John Gerard

### Do not report Prusa3D Slic3r bugs here without confirming it is a problem on a development release of Slic3r, or your issue will be closed. [Development builds of Slic3r](https://dl.slic3r.org/dev). [Prusa3D Issue Tracker](https://github.com/Prusa3D/Slic3r/issues)

**Describe the bug**

**To Reproduce**

**3D Model and Slic3r Configuration Export**
Please upload a ZIP archive containing a copy of the 3D model you are seeing this bug with and a CTRL-E export of the configuration used.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Windows]
 - Version [e.g. 1.3.0]
     - _Do not report Prusa3D Slic3r bugs here without confirming it is a problem on a development release of Slic3r, or your issue will be closed. *Only* use normal Slic3r version IDs._
     - _For -dev versions, use `git describe --tag` or get the hash value for the version you downloaded or `git rev-parse HEAD`_
     - _Use `About->About Slic3r` for release versions._

**Additional context**

**Comment by lordofhyphens** [comment]
Having any M140 or M104 or M109 or M140 commands in your start GCode inhibits the automatic insertion.

What you  need to do is either remove all commands from start gcode and it'll get inserted before the start gcode. 

Or you add one of these commands (or the M104/M140 variants) in your start gcode.
````
M190 S[first_layer_bed_temperature]
M109 S[first_layer_temperature];
````
