### ISSUE TITLE
Auto orientation option

### ISSUE THREAD

**Issue by jmger** [slic3r/Slic3r#5046]
Can there be some sort of option to better/easier aline an object on the Bed surface. I know this is an issue with Simplify3D as well. I will give you an example: I use Shapr3D on my iPad Pro to design my parts. One part is a simple cap design. A flat 3" surface on the top layers. I would like to print the design on the top of the cap as the first layer. So flat on the bed. It is very hard to line this up. I wish I could tell Slic3r that I want to orient the part so it will print flat on the build surface. Right now even though I think the part is laying flat it appears that it must not be completely flat when I check it in the Adaptive layer section. At least Simplify3D, besides entering a specific value, allows you to press an arrow up/down button to move the part in any direction. At least this is a little easier than just entering values. Also simplify3D has a Drop on bed option. This is useful for me to know that the software is placing the full part on the bed and not below the bed surface. 

Thank You

### Do not request features for the Prusa3D fork of Slic3r here without confirming it is applicable to the mainline Slic3r, or your issue will be closed. [Development builds of Slic3r](https://dl.slic3r.org/dev). [Prusa3D Issue Tracker](https://github.com/Prusa3D/Slic3r/issues)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dwillmore** [comment]
There is the 'rotate surface to bed' function which sounds like it would do
exactly what you want.

**Comment by lordofhyphens** [comment]
Right-click on the model in the plater.
![image](https://user-images.githubusercontent.com/31754/111162587-48d6db00-856a-11eb-8d66-3ce0fc12877b.png)
Select the face you want to be on the bed.
![image](https://user-images.githubusercontent.com/31754/111162640-58562400-856a-11eb-8508-300d56ba49e0.png)
