### ISSUE TITLE
wont compile with boost 1.75.0

### ISSUE THREAD

**Issue by ferdna** [slic3r/Slic3r#5055]
Attempting to create directory /tmp/SBo/Slic3r-1.3.0/local-lib
App::cpanminus is up to date. (1.7044)
--> Working on Class::XSAccessor
Fetching http://www.cpan.org/authors/id/S/SM/SMUELLER/Class-XSAccessor-1.19.tar.gz ... OK
Configuring Class-XSAccessor-1.19 ... OK
Building and testing Class-XSAccessor-1.19 ... OK
Successfully installed Class-XSAccessor-1.19
1 distribution installed
Devel::CheckLib is up to date. (1.14)
--> Working on Encode
Fetching http://www.cpan.org/authors/id/D/DA/DANKOGAI/Encode-3.08.tar.gz ... OK
Configuring Encode-3.08 ... OK
Building and testing Encode-3.08 ... OK
Successfully installed Encode-3.08 (upgraded from 3.06)
1 distribution installed
--> Working on Encode::Locale
Fetching http://www.cpan.org/authors/id/G/GA/GAAS/Encode-Locale-1.05.tar.gz ... OK
Configuring Encode-Locale-1.05 ... OK
Building and testing Encode-Locale-1.05 ... OK
Successfully installed Encode-Locale-1.05
1 distribution installed
--> Working on ExtUtils::CppGuess
Fetching http://www.cpan.org/authors/id/E/ET/ETJ/ExtUtils-CppGuess-0.21.tar.gz ... OK
Configuring ExtUtils-CppGuess-0.21 ... OK
==> Found dependencies: Module::Build, Capture::Tiny
--> Working on Module::Build
Fetching http://www.cpan.org/authors/id/L/LE/LEONT/Module-Build-0.4231.tar.gz ... OK
Configuring Module-Build-0.4231 ... OK
Building and testing Module-Build-0.4231 ... OK
Successfully installed Module-Build-0.4231
--> Working on Capture::Tiny
Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/Capture-Tiny-0.48.tar.gz ... OK
Configuring Capture-Tiny-0.48 ... OK
Building and testing Capture-Tiny-0.48 ... OK
Successfully installed Capture-Tiny-0.48
Building and testing ExtUtils-CppGuess-0.21 ... OK
Successfully installed ExtUtils-CppGuess-0.21
3 distributions installed
--> Working on ExtUtils::MakeMaker
Fetching http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.60.tar.gz ... OK
Configuring ExtUtils-MakeMaker-7.60 ... OK
Building and testing ExtUtils-MakeMaker-7.60 ... OK
Successfully installed ExtUtils-MakeMaker-7.60 (upgraded from 7.44)
1 distribution installed
--> Working on ExtUtils::ParseXS
Fetching http://www.cpan.org/authors/id/S/SM/SMUELLER/ExtUtils-ParseXS-3.35.tar.gz ... OK
Configuring ExtUtils-ParseXS-3.35 ... OK
Building and testing ExtUtils-ParseXS-3.35 ... OK
Successfully installed ExtUtils-ParseXS-3.35 (downgraded from 3.40)
1 distribution installed
File::Basename is up to date. (2.85)
File::Spec is up to date. (3.78)
--> Working on Getopt::Long
Fetching http://www.cpan.org/authors/id/J/JV/JV/Getopt-Long-2.52.tar.gz ... OK
Configuring Getopt-Long-2.52 ... OK
Building and testing Getopt-Long-2.52 ... OK
Successfully installed Getopt-Long-2.52 (upgraded from 2.51)
1 distribution installed
--> Working on IO::Scalar
Fetching http://www.cpan.org/authors/id/C/CA/CAPOEIRAB/IO-Stringy-2.113.tar.gz ... OK
Configuring IO-Stringy-2.113 ... OK
Building IO-Stringy-2.113 ... OK
Successfully installed IO-Stringy-2.113
1 distribution installed
--> Working on Module::Build::WithXSpp
Fetching http://www.cpan.org/authors/id/S/SM/SMUELLER/Module-Build-WithXSpp-0.14.tar.gz ... OK
Configuring Module-Build-WithXSpp-0.14 ... OK
==> Found dependencies: ExtUtils::XSpp
--> Working on ExtUtils::XSpp
Fetching http://www.cpan.org/authors/id/S/SM/SMUELLER/ExtUtils-XSpp-0.18.tar.gz ... OK
Configuring ExtUtils-XSpp-0.18 ... OK
==> Found dependencies: Test::Base, Test::Differences
--> Working on Test::Base
Fetching http://www.cpan.org/authors/id/I/IN/INGY/Test-Base-0.89.tar.gz ... OK
Configuring Test-Base-0.89 ... OK
==> Found dependencies: Spiffy, Algorithm::Diff, Text::Diff
--> Working on Spiffy
Fetching http://www.cpan.org/authors/id/I/IN/INGY/Spiffy-0.46.tar.gz ... OK
Configuring Spiffy-0.46 ... OK
Building and testing Spiffy-0.46 ... OK
Successfully installed Spiffy-0.46
--> Working on Algorithm::Diff
Fetching http://www.cpan.org/authors/id/R/RJ/RJBS/Algorithm-Diff-1.201.tar.gz ... OK
Configuring Algorithm-Diff-1.201 ... OK
Building and testing Algorithm-Diff-1.201 ... OK
Successfully installed Algorithm-Diff-1.201
--> Working on Text::Diff
Fetching http://www.cpan.org/authors/id/N/NE/NEILB/Text-Diff-1.45.tar.gz ... OK
Configuring Text-Diff-1.45 ... OK
Building and testing Text-Diff-1.45 ... OK
Successfully installed Text-Diff-1.45
Building and testing Test-Base-0.89 ... OK
Successfully installed Test-Base-0.89
--> Working on Test::Differences
Fetching http://www.cpan.org/authors/id/D/DC/DCANTRELL/Test-Differences-0.67.tar.gz ... OK
Configuring Test-Differences-0.67 ... OK
Building and testing Test-Differences-0.67 ... OK
Successfully installed Test-Differences-0.67
Building and testing ExtUtils-XSpp-0.18 ... OK
Successfully installed ExtUtils-XSpp-0.18
Building and testing Module-Build-WithXSpp-0.14 ... OK
Successfully installed Module-Build-WithXSpp-0.14
7 distributions installed
Moo is up to date. (2.004004)
POSIX is up to date. (1.94)
Scalar::Util is up to date. (1.55)
Test::Harness is up to date. (3.42)
--> Working on Test::More
Fetching http://www.cpan.org/authors/id/E/EX/EXODIST/Test-Simple-1.302183.tar.gz ... OK
Configuring Test-Simple-1.302183 ... OK
Building and testing Test-Simple-1.302183 ... OK
Successfully installed Test-Simple-1.302183 (upgraded from 1.302175)
1 distribution installed
Thread::Queue is up to date. (3.14)
Thread::Semaphore is up to date. (2.13)
Time::HiRes is up to date. (1.9764)
Unicode::Normalize is up to date. (1.27)
--> Working on threads
Fetching http://www.cpan.org/authors/id/J/JD/JDHEDDEN/threads-2.21.tar.gz ... OK
Configuring threads-2.21 ... OK
Building and testing threads-2.21 ... OK
Successfully installed threads-2.21 (downgraded from 2.25)
1 distribution installed
threads::shared is up to date. (1.61)
cpanm (App::cpanminus) 1.7044 on perl 5.032001 built for x86_64-linux-thread-multi
Work directory is /root/.cpanm/work/1615004113.26106
You have make /usr/bin/make
You have /usr/bin/wget
You have /bin/tar: tar (GNU tar) 1.33
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Entering /tmp/SBo/Slic3r-1.3.0/xs
Checking if you have ExtUtils::Install 1.46 ... Yes (2.14)
Checking if you have Module::Build 0.38 ... Yes (0.4231)
Running Build.PL
--> Working on ./xs
Configuring /tmp/SBo/Slic3r-1.3.0/xs ... Checking prerequisites...
  build_requires:
    !  ExtUtils::Typemaps::Basic is not installed
    !  ExtUtils::Typemaps::Default is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Slic3r-XS' version '0.01'
Checking dependencies from MYMETA.json ...
Checking if you have ExtUtils::ParseXS 3.35 ... Yes (3.35)
Checking if you have ExtUtils::Typemaps 1.00 ... Yes (3.35)
Checking if you have Test::More 0 ... Yes (1.302183)
Checking if you have ExtUtils::XSpp 0.18 ... Yes (0.18)
Checking if you have ExtUtils::Typemaps::Default 1.05 ... No
Checking if you have ExtUtils::Typemaps::Basic 1.05 ... No
Checking if you have Module::Build 0.3601 ... Yes (0.4231)
Searching ExtUtils::Typemaps::Default (1.05) on cpanmetadb ...
OK
==> Found dependencies: ExtUtils::Typemaps::Default, ExtUtils::Typemaps::Basic
--2021-03-05 21:15:14--  http://cpanmetadb.plackperl.org/v1.0/package/ExtUtils::Typemaps::Default
Resolving cpanmetadb.plackperl.org (cpanmetadb.plackperl.org)... 151.101.182.217
Connecting to cpanmetadb.plackperl.org (cpanmetadb.plackperl.org)|151.101.182.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 562 [text/yaml]
Saving to: ‘STDOUT’

     0K                                                       100%  132M=0s

2021-03-05 21:15:14 (132 MB/s) - written to stdout [562/562]

--> Working on ExtUtils::Typemaps::Default
Fetching http://www.cpan.org/authors/id/S/SM/SMUELLER/ExtUtils-Typemaps-Default-1.05.tar.gz ... --2021-03-05 21:15:14--  http://www.cpan.org/authors/id/S/SM/SMUELLER/ExtUtils-Typemaps-Default-1.05.tar.gz
Resolving www.cpan.org (www.cpan.org)... 151.101.182.132, 2a04:4e42:2b::644
Connecting to www.cpan.org (www.cpan.org)|151.101.182.132|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9327 (9.1K) [application/x-gzip]
Saving to: ‘ExtUtils-Typemaps-Default-1.05.tar.gz’

     0K .........                                             100% 8.08M=0.001s

2021-03-05 21:15:15 (8.08 MB/s) - ‘ExtUtils-Typemaps-Default-1.05.tar.gz’ saved [9327/9327]

Unpacking ExtUtils-Typemaps-Default-1.05.tar.gz
OK
ExtUtils-Typemaps-Default-1.05
ExtUtils-Typemaps-Default-1.05/Build.PL
ExtUtils-Typemaps-Default-1.05/META.yml
ExtUtils-Typemaps-Default-1.05/MANIFEST
ExtUtils-Typemaps-Default-1.05/META.json
ExtUtils-Typemaps-Default-1.05/MANIFEST.SKIP
ExtUtils-Typemaps-Default-1.05/Changes
ExtUtils-Typemaps-Default-1.05/lib
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemap
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemap/Basic.pm
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemap/ObjectMap.pm
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemap/Default.pm
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemap/STL.pm
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemap/STL
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemap/STL/String.pm
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemap/STL/Vector.pm
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemaps
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemaps/Basic.pm
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemaps/ObjectMap.pm
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemaps/Default.pm
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemaps/STL.pm
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemaps/STL
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemaps/STL/String.pm
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemaps/STL/List.pm
ExtUtils-Typemaps-Default-1.05/lib/ExtUtils/Typemaps/STL/Vector.pm
ExtUtils-Typemaps-Default-1.05/t
ExtUtils-Typemaps-Default-1.05/t/001_basic.t
Entering ExtUtils-Typemaps-Default-1.05
Checking configure dependencies from META.json
Checking if you have Module::Build 0.40 ... Yes (0.4231)
Checking if you have ExtUtils::Install 1.46 ... Yes (2.14)
Running Build.PL
Configuring ExtUtils-Typemaps-Default-1.05 ... Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'ExtUtils-Typemaps-Default' version '1.05'
Checking dependencies from MYMETA.json ...
Checking if you have Module::Build 0 ... Yes (0.4231)
Checking if you have Test::More 0 ... Yes (1.302183)
Checking if you have ExtUtils::Typemaps 3.18_03 ... Yes (3.35)
OK
Building and testing ExtUtils-Typemaps-Default-1.05 ... Building ExtUtils-Typemaps-Default
t/001_basic.t .. ok
All tests successful.
Files=1, Tests=26,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.08 cusr  0.01 csys =  0.12 CPU)
Result: PASS
Building ExtUtils-Typemaps-Default
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/ExtUtils/Typemaps/Basic.pm
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/ExtUtils/Typemaps/STL.pm
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/ExtUtils/Typemaps/Default.pm
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/ExtUtils/Typemaps/ObjectMap.pm
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/ExtUtils/Typemaps/STL/List.pm
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/ExtUtils/Typemaps/STL/Vector.pm
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/ExtUtils/Typemaps/STL/String.pm
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/ExtUtils/Typemap/Basic.pm
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/ExtUtils/Typemap/STL.pm
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/ExtUtils/Typemap/Default.pm
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/ExtUtils/Typemap/ObjectMap.pm
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/ExtUtils/Typemap/STL/Vector.pm
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/ExtUtils/Typemap/STL/String.pm
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/man/man3/ExtUtils::Typemaps::ObjectMap.3
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/man/man3/ExtUtils::Typemaps::Default.3
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/man/man3/ExtUtils::Typemaps::STL.3
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/man/man3/ExtUtils::Typemap::STL::Vector.3
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/man/man3/ExtUtils::Typemap::Default.3
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/man/man3/ExtUtils::Typemaps::STL::String.3
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/man/man3/ExtUtils::Typemap::ObjectMap.3
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/man/man3/ExtUtils::Typemap::STL.3
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/man/man3/ExtUtils::Typemap::STL::String.3
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/man/man3/ExtUtils::Typemap::Basic.3
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/man/man3/ExtUtils::Typemaps::STL::List.3
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/man/man3/ExtUtils::Typemaps::Basic.3
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/man/man3/ExtUtils::Typemaps::STL::Vector.3
OK
Successfully installed ExtUtils-Typemaps-Default-1.05
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/x86_64-linux-thread-multi/.meta/ExtUtils-Typemaps-Default-1.05/install.json
Installing /tmp/SBo/Slic3r-1.3.0/local-lib/lib/perl5/x86_64-linux-thread-multi/.meta/ExtUtils-Typemaps-Default-1.05/MYMETA.json
Searching ExtUtils::Typemaps::Basic (1.05) on cpanmetadb ...
--2021-03-05 21:15:15--  http://cpanmetadb.plackperl.org/v1.0/package/ExtUtils::Typemaps::Basic
Resolving cpanmetadb.plackperl.org (cpanmetadb.plackperl.org)... 151.101.182.217
Connecting to cpanmetadb.plackperl.org (cpanmetadb.plackperl.org)|151.101.182.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 562 [text/yaml]
Saving to: ‘STDOUT’

     0K                                                       100%  230M=0s

2021-03-05 21:15:16 (230 MB/s) - written to stdout [562/562]

Already tried ExtUtils-Typemaps-Default-1.05. Skipping.
Building and testing Slic3r-XS-0.01 ... Building Slic3r-XS
Processing XS typemap files...
Generating main XS file...
g++ -I/usr/lib64/perl5/CORE -fPIC -xc++ -Isrc/libslic3r -DHAS_BOOL -DNOGDI -DSLIC3RXS -DBOOST_ASIO_DISABLE_KQUEUE -Dexprtk_disable_rtl_io_file -Dexprtk_disable_return_statement -Dexprtk_disable_rtl_vecops -Dexprtk_disable_string_capabilities -Dexprtk_disable_enhanced_features -std=gnu++11 -DBOOST_LIBS -DNDEBUG -O -Wno-undefined-var-template -Isrc -Ibuildtmp -c -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -fPIC -o src/libslic3r/Log.o src/libslic3r/Log.cpp
g++ -I/usr/lib64/perl5/CORE -fPIC -xc++ -Isrc/libslic3r -DHAS_BOOL -DNOGDI -DSLIC3RXS -DBOOST_ASIO_DISABLE_KQUEUE -Dexprtk_disable_rtl_io_file -Dexprtk_disable_return_statement -Dexprtk_disable_rtl_vecops -Dexprtk_disable_string_capabilities -Dexprtk_disable_enhanced_features -std=gnu++11 -DBOOST_LIBS -DNDEBUG -O -Wno-undefined-var-template -Isrc -Ibuildtmp -c -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -fPIC -o src/libslic3r/SLAPrint.o src/libslic3r/SLAPrint.cpp
src/libslic3r/SLAPrint.cpp: In member function ‘void Slic3r::SLAPrint::slice()’:
src/libslic3r/SLAPrint.cpp:74:57: error: ‘_1’ was not declared in this scope
   74 |             boost::bind(&SLAPrint::_infill_layer, this, _1, fill.get()),
      |                                                         ^~
src/libslic3r/SLAPrint.cpp:74:57: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/advance.hpp:11,
                 from /usr/include/boost/next_prior.hpp:25,
                 from /usr/include/boost/thread/futures/wait_for_any.hpp:20,
                 from /usr/include/boost/thread/future.hpp:41,
                 from /usr/include/boost/thread.hpp:24,
                 from src/libslic3r/libslic3r.h:17,
                 from src/libslic3r/SLAPrint.hpp:4,
                 from src/libslic3r/SLAPrint.cpp:1:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/boost/system/detail/error_category.hpp:17,
                 from /usr/include/boost/system/detail/error_code.hpp:13,
                 from /usr/include/boost/system/error_code.hpp:13,
                 from /usr/include/boost/system/system_error.hpp:11,
                 from /usr/include/boost/thread/exceptions.hpp:22,
                 from /usr/include/boost/thread/pthread/thread_data.hpp:10,
                 from /usr/include/boost/thread/thread_only.hpp:17,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from src/libslic3r/libslic3r.h:17,
                 from src/libslic3r/SLAPrint.hpp:4,
                 from src/libslic3r/SLAPrint.cpp:1:
/usr/include/c++/10.2.0/functional:221:34: note:   ‘std::placeholders::_1’
  221 |     extern const _Placeholder<1> _1;
      |                                  ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/advance.hpp:11,
                 from /usr/include/boost/next_prior.hpp:25,
                 from /usr/include/boost/thread/futures/wait_for_any.hpp:20,
                 from /usr/include/boost/thread/future.hpp:41,
                 from /usr/include/boost/thread.hpp:24,
                 from src/libslic3r/libslic3r.h:17,
                 from src/libslic3r/SLAPrint.hpp:4,
                 from src/libslic3r/SLAPrint.cpp:1:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/boost/bind/bind.hpp:2335,
                 from /usr/include/boost/thread/detail/thread.hpp:33,
                 from /usr/include/boost/thread/thread_only.hpp:22,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from src/libslic3r/libslic3r.h:17,
                 from src/libslic3r/SLAPrint.hpp:4,
                 from src/libslic3r/SLAPrint.cpp:1:
/usr/include/boost/bind/placeholders.hpp:58:38: note:   ‘boost::placeholders::_1’
   58 | BOOST_STATIC_CONSTEXPR boost::arg<1> _1;
      |                                      ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/advance.hpp:11,
                 from /usr/include/boost/next_prior.hpp:25,
                 from /usr/include/boost/thread/futures/wait_for_any.hpp:20,
                 from /usr/include/boost/thread/future.hpp:41,
                 from /usr/include/boost/thread.hpp:24,
                 from src/libslic3r/libslic3r.h:17,
                 from src/libslic3r/SLAPrint.hpp:4,
                 from src/libslic3r/SLAPrint.cpp:1:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-undefined-var-template’ may have been intended to silence earlier diagnostics
error building src/libslic3r/SLAPrint.o from 'src/libslic3r/SLAPrint.cpp' at /usr/share/perl5/ExtUtils/CBuilder/Base.pm line 185.
! Installing ./xs failed. See /root/.cpanm/work/1615004113.26106/build.log for details. Retry with --force to force install it.
FAIL
1 distribution installed
The XS/C++ code failed to compile, aborting

**Comment by lordofhyphens** [comment]
@ferdna Try it now, I merged a PR having to deal with `_1`.

**Comment by ferdna** [comment]
> @ferdna Try it now, I merged a PR having to deal with `_1`.

it works now. thank you so much. :)
