### ISSUE TITLE
Thread 2 terminated abnormally crash

### ISSUE THREAD

**Issue by Tyql** [slic3r/Slic3r#5059]
**Describe the bug**
Slic3r crashes when I'm scaling the object

**To Reproduce**
1. Add .STL
2. Select object
3. Scale > Z Axis any %
4. Scale > Y or X Axis any %
4. Program crashes.

**3D Model and Slic3r Configuration Export**
[Bug Report.zip](https://github.com/slic3r/Slic3r/files/6095873/Bug.Report.zip)

**Expected behavior**
Not crashing

**Screenshots**
![error message](https://user-images.githubusercontent.com/11340048/110217082-3aa90080-7e80-11eb-83cd-00108cb4e40a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64 Bit
 - Version: 1.3.0

**Comment by lordofhyphens** [comment]
Well, it isn't crashing on Linux, so there's that.

**Comment by lordofhyphens** [comment]
Didn't crash either with the build for 0536b14f.

https://dl.slic3r.org/dev/win/

**Comment by lordofhyphens** [comment]
I need some more information about what you were doing here; as loading the provided configuration and model and doing what you said did not cause a crash on current dev version. 

Closing, will re-open if you can reproduce on current -dev.
