### ISSUE TITLE
Slicer Fails to Start

### ISSUE THREAD

**Issue by adamgranthendry** [slic3r/Slic3r#5100]
### 3D Slicer Version
Slicer-4.11.20210226-win-amd64

### Operating System
Windows 10 Enterprise, x64, Build 1909

### Behavior
Slicer fails to start

![image](https://user-images.githubusercontent.com/77850046/131268504-86fb8c2b-33f9-497d-a1dd-2b95cce0cf99.png)

Uninstalling and reinstalling does not resolve this issue.

**Comment by dwillmore** [comment]
You have found the wrong github, I'm afraid.  You're reporting a bug for https://download.slicer.org/ which is quite distinct from https://slic3r.org/download/ which is this github.
