### ISSUE TITLE
Can the slic3r connect to 3D scanner software？

### ISSUE THREAD

**Issue by huminlian** [slic3r/Slic3r#5123]
### Do not request features for the Prusa3D fork of Slic3r here without confirming it is applicable to the mainline Slic3r, or your issue will be closed. [Development builds of Slic3r](https://dl.slic3r.org/dev). [Prusa3D Issue Tracker](https://github.com/Prusa3D/Slic3r/issues)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I'm often using a 3D scanner to scan some characters and print them. So, I wish the Slic3r can import the models from the [3D scanner app](https://www.revopoint3d.com/download/3d-scanner-app/) and slice the models directly and then print them.

**Comment by lordofhyphens** [comment]
If the 3D Scanner application outputs in a mesh format that Slic3r understands, then it can attempt to slice it, but those scan applications tend to output really dirty meshes that often need to be manually edited/fixed to be printable.
