### ISSUE TITLE
Decimal commas

### ISSUE THREAD

**Issue by henrikbrixandersen** [slic3r/Slic3r#538]
Reported on IRC: < hurzl> slic3r doesn't parse and writes decimal commas!

I suggest we continue to use decimal points internally, but change presentation/input to the the locale-specific decimal separator from localeconv().

**Comment by lordofhyphens** [comment]
@henrikbrixandersen  @ppisar is this still an issue on your locales? Kinda important for me if I'm going to be working on internationality.

**Comment by ppisar** [comment]
I do not use slic3r. I just installed it now into Fedora 26 (perl-5.24.1) and
it crashes somehwere in wxWindow::DoSetSize() regardless of locale now.
Because of this unrelated WxWindows bug I cannot provide any datails.

**Comment by lordofhyphens** [comment]
Will keep this in mind when I work on the C++ UI (and see what I can do to respect the current locale).
